# Procesado ETL de datos de Homicidios en siniestros viales en la Ciudad de Buenos Aires (2016-2021)

#### Homicidios

Esta base de datos contiene registros sobre homicidios en siniestros viales acaecidos en la Ciudad de Buenos Aires durante el periodo 2016-2021, acontinuación se presenta ol procesado ETL de estos datos para poder utilizarlos posteriormente en el análisis exploratorio de datos.

Fuente de los datos:  https://cdn.buenosaires.gob.ar/datosabiertos/datasets/transporte-y-obras-publicas/victimas-siniestros-viales/homicidios.xlsx

### Librerias utilizadas

In [136]:
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

### Carga de los datos

Primero visualizamos el nombre de las hojas del archivo, para luego utilizar pandas y cargarlas correctamente.

La base de datos `homidicios.xslx` dispone de 4 hojas de interes, una llamada `HECHOS`,otra llamada `VICTIMAS` que son tablas y las demas correspondena a el diccionario de datos de cada una, por lo tanto, se procedera a cargar estas tablas y realizar una exploración individual.

In [137]:
hechos = pd.read_excel("./data/homicidios.xlsx", sheet_name="HECHOS")
victimas = pd.read_excel("./data/homicidios.xlsx", sheet_name="VICTIMAS")

### Procesamiento de la tabla `hechos`

In [138]:
hechos

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,NaN,"FERNANDEZ DE LA CRUZ, F., GRAL. AV.","PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...",8,Point (98896.78238426 93532.43437792),-58.47533969,-34.68757022,MOTO-AUTO,MOTO,AUTO
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,NaN,DE LOS CORRALES AV.,"PAZ, GRAL. AV. y DE LOS CORRALES AV.",9,Point (95832.05571093 95505.41641999),-58.50877521,-34.66977709,AUTO-PASAJEROS,AUTO,PASAJEROS
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,2034.0,NaN,ENTRE RIOS AV. 2034,1,Point (106684.29090040 99706.57687843),-58.39040293,-34.63189362,MOTO-AUTO,MOTO,AUTO
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,NaN,"VILLEGAS, CONRADO, GRAL.","LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.",8,Point (99840.65224780 94269.16534422),-58.46503904,-34.68092974,MOTO-SD,MOTO,SD
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,NaN,"SAENZ PE?A, LUIS, PRES.","SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.",1,Point (106980.32827929 100752.16915795),-58.38718297,-34.62246630,MOTO-PASAJEROS,MOTO,PASAJEROS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,NaN,MOM,RIESTRA AV. y MOM,7,Point (102728.60090138 98186.24929177),-58.43353773,-34.64561636,MOTO-AUTO,MOTO,AUTO
692,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,NaN,LACARRA AV.,"DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.",9,Point (99624.29795829 97569.69801131),-58.46739825,-34.65117757,MOTO-AUTO,MOTO,AUTO
693,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,NaN,TERRADA,GAONA AV. y TERRADA,11,Point (99116.45492358 101045.23284826),-58.47293407,-34.61984745,MOTO-CARGAS,MOTO,CARGAS
694,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,4071.0,NaN,"PERON, EVA AV. 4071",9,Point (99324.54463985 97676.26932409),-58.47066794,-34.65021673,AUTO-CARGAS,AUTO,CARGAS
695,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,709.0,NaN,PADRE CARLOS MUGICA 709,1,Point (107664.16647795 104708.63962087),-58.37976155,-34.58679619,BICICLETA-AUTO,BICICLETA,AUTO

In [139]:
hechos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     696 non-null    object
 1   N_VICTIMAS             696 non-null    int64
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64
 4   MM                     696 non-null    int64
 5   DD                     696 non-null    int64
 6   HORA                   696 non-null    object
 7   HH                     696 non-null    object
 8   LUGAR_DEL_HECHO        696 non-null    object
 9   TIPO_DE_CALLE          696 non-null    object
 10  Calle                  695 non-null    object
 11  Altura                 129 non-null    float64
 12  Cruce                  525 non-null    object
 13  Dirección Normalizada  688 non-null    object
 14  COMUNA                 696 non-null    int64
 15  XY (CABA)              696 non-null    object
 16  pos x                  696 non-null    object
 17  pos y                  696 non-null    object
 18  PARTICIPANTES          696 non-null    object
 19  VICTIMA                696 non-null    object
 20  ACUSADO                696 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(5), object(14)
memory usage: 114.3+ KB

### Reporte Preliminar

La tabla `hechos` contiene un total de 696 entradas, distribuidas en 21 columnas. A continuación, se presenta un análisis preliminar de cada variable:

1. **ID**: Todos los registros están completos (696 no nulos), deberia contener un identificador único para cada hecho.

2. **N_VICTIMAS**: Con 696 valores no nulos, esta variable numérica podría ser utilizada para analizar la distribución del número de víctimas por incidente, permitiendo identificar tendencias o patrones en la gravedad de los mismos.

3. **FECHA**: También completa para todos los registros, proporciona una marca temporal precisa de cada incidente. Esta variable es fundamental para análisis temporales, permitiendo explorar patrones estacionales, mensuales o diarios.

4. **AAAA**, **MM**, **DD**: Estas columnas desglosan la fecha del incidente en año, mes y día, respectivamente, facilitando análisis específicos por periodos de tiempo. La completitud de estos campos asegura una base sólida para dicho análisis.

5. **HORA**, **HH**: Al igual que con la fecha, estas variables permiten un análisis detallado del momento del día en que ocurren los incidentes. La variable `HORA` parece contener la hora en formato objeto, mientras que `HH` podría ser una representación específica o un desglose adicional de la misma.

6. **LUGAR_DEL_HECHO**, **TIPO_DE_CALLE**, **Calle**: Estas variables aportan información detallada sobre la ubicación de los incidentes. La casi total completitud de 'Calle' (695 no nulos) y la totalidad en 'LUGAR_DEL_HECHO' y 'TIPO_DE_CALLE' sugieren un buen fundamento para análisis geográficos.

7. **Altura**: Con solo 129 registros no nulos, esta variable presenta un alto grado de valores faltantes, lo que requiere una evaluación cuidadosa para su uso en análisis detallados de localización.

8. **Cruce**: Con 525 valores no nulos, esta variable complementa la información de ubicación, aunque también presenta un número significativo de entradas faltantes. Podría requerir técnicas de imputación o un análisis específico para las entradas completas.

9. **Dirección Normalizada**: Con 688 valores no nulos, ofrece una versión estandarizada de las direcciones de los incidentes, lo que puede ser útil para unificar y comparar datos de localización.

10. **COMUNA**: Completa para todos los registros, esta variable numérica puede facilitar el análisis por regiones específicas dentro de la jurisdicción de los incidentes.

11. **XY (CABA)**, **pos x**, **pos y**: Estas variables, completas en todos los registros, proporcionan coordenadas específicas para análisis geoespaciales detallados, permitiendo visualizaciones y estudios de concentración de incidentes.

12. **PARTICIPANTES**, **VICTIMA**, **ACUSADO**: Con información completa en todas estas columnas, ofrecen un contexto detallado sobre los involucrados en cada incidente, abriendo posibilidades para análisis demográficos y de relaciones entre participantes.


Ahora, con este conocimiento de las variables que contiene la tabla `hechos`, se procederá a realizar un análisis individual y grupal de las mismas para verificar su integridad, valores nulos, duplicados y se comprobara la necesidad de realizar transformaciones

### ID

In [140]:
# Verificamos ID duplicados

hechos["ID"].duplicated().sum()

0

Cada hecho tiene un identificador único,

### N_VICTIMAS

In [141]:
# Verificamos valores únicos

hechos['N_VICTIMAS'].unique()

array([1, 2, 3], dtype=int64)

### FECHA

In [142]:
print(hechos['FECHA'].head())
print(hechos['FECHA'].describe())
print(hechos['FECHA'].dtype)

0   2016-01-01
1   2016-01-02
2   2016-01-03
3   2016-01-10
4   2016-01-21
Name: FECHA, dtype: datetime64[ns]
count                              696
mean     2018-09-14 05:12:24.827586048
min                2016-01-01 00:00:00
25%                2017-04-02 12:00:00
50%                2018-07-12 12:00:00
75%                2020-01-04 06:00:00
max                2021-12-30 00:00:00
Name: FECHA, dtype: object
datetime64[ns]

El formato de fecha identificado es "yyyy-mm-dd" y el tipo de dato es datetime64[ns] con un rango de 2016 a 2021, no se encuentra ninguna inconsistencia en esta variable, por lo que no se realizaran transformaciones.

### AAAA, MM, DD, HORA, HH

In [143]:
hechos['HORA']

0      04:00:00
1      01:15:00
2      07:00:00
3      00:00:00
4      05:20:00
         ...
691    17:10:00
692    01:10:00
693    00:43:00
694    10:30:00
695    06:10:00
Name: HORA, Length: 696, dtype: object

In [144]:
print(hechos['AAAA'].unique())
print(hechos['MM'].unique())
print(hechos['DD'].unique())
print(hechos['HORA'].unique())
print(hechos['HH'].unique())

[2016 2017 2018 2019 2020 2021]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3 10 21 24 29  8 14 15 17 28  4 12 13 19 23 30 31 11 20 22 25 26
 16 18 27  7  9  5  6]
[datetime.time(4, 0) datetime.time(1, 15) datetime.time(7, 0)
 datetime.time(0, 0) datetime.time(5, 20) datetime.time(18, 30)
 datetime.time(19, 10) datetime.time(15, 20) datetime.time(1, 20)
 datetime.time(11, 30) datetime.time(5, 14) datetime.time(22, 0)
 datetime.time(16, 54) datetime.time(9, 30) datetime.time(16, 0)
 datetime.time(23, 35) datetime.time(6, 0) datetime.time(4, 50)
 datetime.time(7, 30) datetime.time(9, 35) datetime.time(10, 0)
 datetime.time(17, 30) datetime.time(12, 30) datetime.time(0, 15)
 datetime.time(11, 0) datetime.time(8, 6) datetime.time(1, 50)
 datetime.time(18, 15) datetime.time(19, 40) datetime.time(10, 25)
 datetime.time(5, 30) datetime.time(17, 40) datetime.time(9, 50)
 datetime.time(20, 0) datetime.time(21, 0) datetime.time(20, 30)
 datetime.time(4, 45) datetime.time(14, 0) datetime.time(16, 30)
 datetime.time(18, 11) datetime.time(14, 40) datetime.time(17, 0)
 datetime.time(3, 30) datetime.time(15, 0) datetime.time(6, 40)
 datetime.time(23, 13) datetime.time(16, 20) datetime.time(21, 52)
 datetime.time(23, 1) datetime.time(17, 13) datetime.time(6, 42)
 datetime.time(7, 42) datetime.time(18, 24) datetime.time(20, 46)
 datetime.time(16, 10) datetime.time(0, 10) datetime.time(15, 30)
 datetime.time(6, 12) datetime.time(18, 45) datetime.time(16, 8)
 datetime.time(23, 27) datetime.time(19, 42) datetime.time(23, 37)
 datetime.time(21, 15) datetime.time(0, 5) datetime.time(21, 2)
 datetime.time(8, 22) datetime.time(5, 45) datetime.time(20, 21)
 datetime.time(4, 40) datetime.time(16, 45) datetime.time(11, 20)
 datetime.time(11, 50) datetime.time(20, 20) datetime.time(7, 10)
 datetime.time(9, 0) datetime.time(15, 24) datetime.time(12, 14)
 datetime.time(22, 45) datetime.time(19, 13) datetime.time(2, 30)
 datetime.time(5, 0) datetime.time(0, 39) datetime.time(23, 0)
 datetime.time(2, 58) datetime.time(23, 30) datetime.time(4, 41)
 datetime.time(12, 10) datetime.time(20, 56) datetime.time(22, 20)
 datetime.time(18, 20) datetime.time(20, 35) datetime.time(21, 10)
 datetime.time(15, 42) datetime.time(14, 14) datetime.time(16, 50)
 datetime.time(7, 21) datetime.time(7, 22) datetime.time(6, 16)
 datetime.time(8, 25) datetime.time(10, 40) datetime.time(17, 10)
 datetime.time(19, 0) datetime.time(8, 0) datetime.time(19, 52)
 datetime.time(8, 15) datetime.time(1, 41) datetime.time(16, 18)
 datetime.time(1, 0) datetime.time(3, 10) datetime.time(0, 40)
 datetime.time(13, 56) datetime.time(8, 27, 34) datetime.time(15, 18, 3)
 datetime.time(5, 12, 21) datetime.time(20, 50) datetime.time(17, 5)
 datetime.time(5, 15) datetime.time(21, 57) datetime.time(9, 20)
 datetime.time(2, 15) datetime.time(1, 30) datetime.time(7, 50)
 datetime.time(18, 0) datetime.time(3, 0) datetime.time(9, 40)
 datetime.time(23, 15) datetime.time(6, 15) datetime.time(6, 30)
 datetime.time(18, 16) datetime.time(11, 8, 8) datetime.time(3, 47, 47)
 datetime.time(3, 40) datetime.time(20, 16, 22) datetime.time(8, 30)
 datetime.time(23, 10) datetime.time(9, 24) datetime.time(7, 20)
 datetime.time(13, 29, 30) datetime.time(10, 13) datetime.time(18, 10)
 datetime.time(2, 45) datetime.time(19, 50) datetime.time(14, 15)
 datetime.time(13, 20) datetime.time(23, 20) datetime.time(12, 50)
 datetime.time(22, 38) datetime.time(14, 50) datetime.time(23, 45)
 datetime.time(16, 26) datetime.time(10, 15) datetime.time(22, 40)
 datetime.time(0, 25) datetime.time(12, 49) datetime.time(10, 45)
 datetime.time(22, 30) datetime.time(12, 5) datetime.time(13, 0)
 datetime.time(22, 16, 1) datetime.time(16, 48, 40) datetime.time(8, 50)
 datetime.time(19, 45) datetime.time(7, 45) datetime.time(1, 10)
 datetime.time(4, 53, 8) datetime.time(18, 23, 37)
 datetime.time(9, 32, 17) datetime.time(18, 52, 33) datetime.time(22, 24)
 datetime.time(7, 2, 9) datetime.time(15, 55, 33) datetime.time(1, 5, 38)
 datetime.time(14, 40, 28) datetime.time(6, 12, 20)
 datetime.time(19, 15, 15) datetime.time(12, 14, 10) datetime.time(8, 43)
 datetime.time(11, 45) datetime.time(10, 30) datetime.time(23, 22, 17)
 datetime.time(21, 45) datetime.time(6, 45) datetime.time(11, 15)
 datetime.time(12, 20) datetime.time(2, 0) datetime.time(9, 15)
 datetime.time(21, 25, 41) datetime.time(9, 2) datetime.time(21, 30)
 datetime.time(4, 31, 27) datetime.time(13, 15) '22:50:00' '16:40:00'
 '10:12:00' '09:40:00' '22:30:00' '21:15:00' '02:30:00' '17:50:00'
 datetime.time(5, 10) '10:30:00' '13:30:00' '08:15:00' '20:00:00'
 '01:00:00' '10:15:00' '04:15:00' '07:15:00' '12:30:00' '22:00:00'
 '10:45:00' '00:00:00' '06:00:00' '23:00:00' '04:45:00' '15:45:00'
 '18:00:00' '01:30:00' '13:00:00' '18:15:00' '16:45:00' '23:15:00'
 datetime.time(22, 15) datetime.time(18, 43) '06:30:00' '09:00:00'
 '07:00:00' '03:15:00' datetime.time(19, 15) '18:45:00' '20:30:00'
 '11:15:00' datetime.time(6, 20) datetime.time(16, 15)
 datetime.time(15, 45) datetime.time(17, 50) datetime.time(6, 4)
 datetime.time(7, 15) datetime.time(22, 22) datetime.time(15, 53)
 datetime.time(7, 25) datetime.time(21, 44) '19:20:00'
 datetime.time(16, 36) '17:56:00' '10:34:00' datetime.time(18, 47)
 '08:20:00' '08:41:00' '05:35:00' '00:59:00' '22:20:00'
 datetime.time(10, 50) '05:00:00' '14:25:00' '00:15:00' '00:30:00'
 '17:51:00' datetime.time(8, 58) '18:12:00' '22:02:00' '14:20:00'
 '22:12:00' '03:05:00' '12:13:00' '09:18:00' '11:00:00' '02:15:00'
 '14:49:00' datetime.time(22, 35) '13:34:00' '16:32:00' '03:32:00'
 '19:40:00' '21:12:00' datetime.time(12, 11) '09:14:00' '04:30:00'
 '04:01:00' '03:00:00' '08:26:00' '14:07:00' '21:00:00' '15:42:00'
 datetime.time(20, 15) '09:30:00' datetime.time(8, 5) '05:25:00'
 datetime.time(19, 58) datetime.time(12, 0) datetime.time(19, 34)
 datetime.time(14, 55) datetime.time(3, 16) datetime.time(6, 57)
 datetime.time(21, 1) datetime.time(22, 50)
 datetime.datetime(1900, 1, 2, 0, 0) datetime.time(8, 28)
 datetime.datetime(1900, 1, 14, 7, 12) datetime.time(13, 10)
 datetime.time(7, 32) datetime.time(11, 11) datetime.time(19, 55)
 datetime.time(9, 8) datetime.time(14, 10) datetime.time(22, 46)
 datetime.time(3, 5) datetime.time(12, 45) datetime.time(7, 27)
 datetime.time(17, 20) datetime.time(17, 16) datetime.time(18, 40)
 datetime.time(3, 15) datetime.time(5, 25)
 datetime.datetime(1900, 1, 4, 18, 40) datetime.time(22, 18)
 datetime.time(18, 26) datetime.time(19, 33) datetime.time(4, 20)
 datetime.time(14, 30) 'SD' datetime.time(4, 25) datetime.time(21, 40)
 datetime.time(12, 55) datetime.time(0, 37) datetime.time(11, 29)
 datetime.time(2, 14) datetime.time(18, 42) datetime.time(7, 58)
 datetime.time(5, 35) datetime.time(6, 25) datetime.time(3, 20)
 datetime.time(4, 30) datetime.time(19, 17, 42) datetime.time(1, 45)
 datetime.time(0, 20) datetime.time(6, 50) datetime.time(6, 35)
 datetime.time(17, 19) datetime.time(15, 35) datetime.time(7, 40)
 datetime.time(5, 50) datetime.time(4, 15) datetime.time(10, 20)
 datetime.time(9, 12, 18) datetime.time(1, 4, 26) datetime.time(20, 7, 22)
 datetime.time(6, 10) datetime.time(0, 50) datetime.time(4, 10)
 datetime.time(3, 45) datetime.time(2, 35) datetime.time(18, 5)
 datetime.time(10, 29) datetime.time(11, 40) datetime.time(12, 9)
 datetime.time(17, 24) datetime.time(9, 58) datetime.time(13, 30)
 datetime.time(19, 20) datetime.time(5, 40) datetime.time(14, 44)
 datetime.time(23, 25) datetime.time(7, 16) datetime.time(9, 29)
 datetime.time(17, 15) datetime.time(16, 16) datetime.time(13, 35)
 datetime.time(4, 39) datetime.time(0, 35) datetime.time(10, 10)
 datetime.time(11, 22) datetime.time(15, 40) datetime.time(0, 43)]
[4 1 7 0 5 18 19 15 11 22 16 9 23 6 10 17 12 8 20 21 14 3 2 13 'SD']

`AAAA` contiene el rango de años 2016-2021, `MM` contiene el rango de meses 1-12, `DD` contiene el rango de días 1-31.

Por otra parte, la variable `HORA` contiene registros que no estan en formato 'hh:mm:ss' datetime, se han detectado datos sin definir 'SD', y registros que no estan en el tipo de dato datetime, por lo que se procedera a realizar una transformación de esta variable.
`HH`  contiene el rango de horas 0-23, se observan registros sin definir 'SD'.

In [145]:
from datetime import datetime, time

# Corrección de la función para normalizar la columna HORA


def normalizar_hora(hora):
    if isinstance(hora, str):  # Si el valor es una cadena, convertir a datetime.time
        try:
            hora_dt = datetime.strptime(hora, '%H:%M:%S')
            return hora_dt.strftime('%H:%M')
        except ValueError:
            try:
                # Manejar formato sin segundos
                hora_dt = datetime.strptime(hora, '%H:%M')
                return hora_dt.strftime('%H:%M')
            except ValueError:
                # Devolver como está si no coincide con los formatos esperados
                return hora
    elif isinstance(hora, time):  # Si ya es un objeto datetime.time, convertir a cadena
        return hora.strftime('%H:%M')

    # si es formato datetime.datetime, convertir a NA
    elif isinstance(hora, datetime):
        return pd.NA
    else:
        # Manejar otros tipos no esperados, devolver como está
        return hora


# Aplicar la función de normalización a la columna HORA
hechos['HORA'] = hechos['HORA'].apply(normalizar_hora)

# Tratar 'HH' como nulo para valores 'SD'
hechos['HORA'] = hechos['HORA'].replace('SD', pd.NA)
hechos['HH'] = hechos['HH'].replace('SD', pd.NA)


# convertir a datetime.time la columna HORA

hechos['HORA'] = pd.to_datetime(
    hechos['HORA'], format='%H:%M', errors='coerce').dt.time

# Eliminar valores nulos para la columna HORA y HH
hechos = hechos.dropna(subset=['HORA', 'HH'])

In [146]:
# Revision final

print(hechos['HORA'].unique())
print(hechos['HH'].unique())

print(hechos['HORA'].isnull().sum())
print(hechos['HH'].isnull().sum())

[datetime.time(4, 0) datetime.time(1, 15) datetime.time(7, 0)
 datetime.time(0, 0) datetime.time(5, 20) datetime.time(18, 30)
 datetime.time(19, 10) datetime.time(15, 20) datetime.time(1, 20)
 datetime.time(11, 30) datetime.time(5, 14) datetime.time(22, 0)
 datetime.time(16, 54) datetime.time(9, 30) datetime.time(16, 0)
 datetime.time(23, 35) datetime.time(6, 0) datetime.time(4, 50)
 datetime.time(7, 30) datetime.time(9, 35) datetime.time(10, 0)
 datetime.time(17, 30) datetime.time(12, 30) datetime.time(0, 15)
 datetime.time(11, 0) datetime.time(8, 6) datetime.time(1, 50)
 datetime.time(18, 15) datetime.time(19, 40) datetime.time(10, 25)
 datetime.time(5, 30) datetime.time(17, 40) datetime.time(9, 50)
 datetime.time(20, 0) datetime.time(21, 0) datetime.time(20, 30)
 datetime.time(4, 45) datetime.time(14, 0) datetime.time(16, 30)
 datetime.time(18, 11) datetime.time(14, 40) datetime.time(17, 0)
 datetime.time(3, 30) datetime.time(15, 0) datetime.time(6, 40)
 datetime.time(23, 13) datetime.time(16, 20) datetime.time(21, 52)
 datetime.time(23, 1) datetime.time(17, 13) datetime.time(6, 42)
 datetime.time(7, 42) datetime.time(18, 24) datetime.time(20, 46)
 datetime.time(16, 10) datetime.time(0, 10) datetime.time(15, 30)
 datetime.time(6, 12) datetime.time(18, 45) datetime.time(16, 8)
 datetime.time(23, 27) datetime.time(19, 42) datetime.time(23, 37)
 datetime.time(21, 15) datetime.time(0, 5) datetime.time(21, 2)
 datetime.time(8, 22) datetime.time(5, 45) datetime.time(20, 21)
 datetime.time(4, 40) datetime.time(16, 45) datetime.time(11, 20)
 datetime.time(11, 50) datetime.time(20, 20) datetime.time(7, 10)
 datetime.time(9, 0) datetime.time(15, 24) datetime.time(12, 14)
 datetime.time(22, 45) datetime.time(19, 13) datetime.time(2, 30)
 datetime.time(5, 0) datetime.time(0, 39) datetime.time(23, 0)
 datetime.time(2, 58) datetime.time(23, 30) datetime.time(4, 41)
 datetime.time(12, 10) datetime.time(20, 56) datetime.time(22, 20)
 datetime.time(18, 20) datetime.time(20, 35) datetime.time(21, 10)
 datetime.time(15, 42) datetime.time(14, 14) datetime.time(16, 50)
 datetime.time(7, 21) datetime.time(7, 22) datetime.time(6, 16)
 datetime.time(8, 25) datetime.time(10, 40) datetime.time(17, 10)
 datetime.time(19, 0) datetime.time(8, 0) datetime.time(19, 52)
 datetime.time(8, 15) datetime.time(1, 41) datetime.time(16, 18)
 datetime.time(1, 0) datetime.time(3, 10) datetime.time(0, 40)
 datetime.time(13, 56) datetime.time(8, 27) datetime.time(15, 18)
 datetime.time(5, 12) datetime.time(20, 50) datetime.time(17, 5)
 datetime.time(5, 15) datetime.time(21, 57) datetime.time(9, 20)
 datetime.time(2, 15) datetime.time(1, 30) datetime.time(7, 50)
 datetime.time(18, 0) datetime.time(3, 0) datetime.time(9, 40)
 datetime.time(23, 15) datetime.time(6, 15) datetime.time(6, 30)
 datetime.time(18, 16) datetime.time(11, 8) datetime.time(3, 47)
 datetime.time(3, 40) datetime.time(20, 16) datetime.time(8, 30)
 datetime.time(23, 10) datetime.time(9, 24) datetime.time(7, 20)
 datetime.time(13, 29) datetime.time(10, 13) datetime.time(18, 10)
 datetime.time(2, 45) datetime.time(19, 50) datetime.time(14, 15)
 datetime.time(13, 20) datetime.time(23, 20) datetime.time(12, 50)
 datetime.time(22, 38) datetime.time(14, 50) datetime.time(23, 45)
 datetime.time(16, 26) datetime.time(10, 15) datetime.time(22, 40)
 datetime.time(0, 25) datetime.time(12, 49) datetime.time(10, 45)
 datetime.time(22, 30) datetime.time(12, 5) datetime.time(13, 0)
 datetime.time(22, 16) datetime.time(16, 48) datetime.time(8, 50)
 datetime.time(19, 45) datetime.time(7, 45) datetime.time(1, 10)
 datetime.time(4, 53) datetime.time(18, 23) datetime.time(9, 32)
 datetime.time(18, 52) datetime.time(22, 24) datetime.time(7, 2)
 datetime.time(15, 55) datetime.time(1, 5) datetime.time(19, 15)
 datetime.time(8, 43) datetime.time(11, 45) datetime.time(10, 30)
 datetime.time(23, 22) datetime.time(21, 45) datetime.time(6, 45)
 datetime.time(11, 15) datetime.time(12, 20) datetime.time(2, 0)
 datetime.time(9, 15) datetime.time(21, 25) datetime.time(9, 2)
 datetime.time(21, 30) datetime.time(4, 31) datetime.time(13, 15)
 datetime.time(22, 50) datetime.time(16, 40) datetime.time(10, 12)
 datetime.time(17, 50) datetime.time(5, 10) datetime.time(13, 30)
 datetime.time(4, 15) datetime.time(7, 15) datetime.time(15, 45)
 datetime.time(22, 15) datetime.time(18, 43) datetime.time(3, 15)
 datetime.time(6, 20) datetime.time(16, 15) datetime.time(6, 4)
 datetime.time(22, 22) datetime.time(15, 53) datetime.time(7, 25)
 datetime.time(21, 44) datetime.time(19, 20) datetime.time(16, 36)
 datetime.time(17, 56) datetime.time(10, 34) datetime.time(18, 47)
 datetime.time(8, 20) datetime.time(8, 41) datetime.time(5, 35)
 datetime.time(0, 59) datetime.time(10, 50) datetime.time(14, 25)
 datetime.time(0, 30) datetime.time(17, 51) datetime.time(8, 58)
 datetime.time(18, 12) datetime.time(22, 2) datetime.time(14, 20)
 datetime.time(22, 12) datetime.time(3, 5) datetime.time(12, 13)
 datetime.time(9, 18) datetime.time(14, 49) datetime.time(22, 35)
 datetime.time(13, 34) datetime.time(16, 32) datetime.time(3, 32)
 datetime.time(21, 12) datetime.time(12, 11) datetime.time(9, 14)
 datetime.time(4, 30) datetime.time(4, 1) datetime.time(8, 26)
 datetime.time(14, 7) datetime.time(20, 15) datetime.time(8, 5)
 datetime.time(5, 25) datetime.time(19, 58) datetime.time(12, 0)
 datetime.time(19, 34) datetime.time(14, 55) datetime.time(3, 16)
 datetime.time(6, 57) datetime.time(21, 1) datetime.time(8, 28)
 datetime.time(13, 10) datetime.time(7, 32) datetime.time(11, 11)
 datetime.time(19, 55) datetime.time(9, 8) datetime.time(14, 10)
 datetime.time(22, 46) datetime.time(12, 45) datetime.time(7, 27)
 datetime.time(17, 20) datetime.time(17, 16) datetime.time(18, 40)
 datetime.time(22, 18) datetime.time(18, 26) datetime.time(19, 33)
 datetime.time(4, 20) datetime.time(14, 30) datetime.time(4, 25)
 datetime.time(21, 40) datetime.time(12, 55) datetime.time(0, 37)
 datetime.time(11, 29) datetime.time(2, 14) datetime.time(18, 42)
 datetime.time(7, 58) datetime.time(6, 25) datetime.time(3, 20)
 datetime.time(19, 17) datetime.time(1, 45) datetime.time(0, 20)
 datetime.time(6, 50) datetime.time(6, 35) datetime.time(17, 19)
 datetime.time(15, 35) datetime.time(7, 40) datetime.time(5, 50)
 datetime.time(10, 20) datetime.time(9, 12) datetime.time(1, 4)
 datetime.time(20, 7) datetime.time(6, 10) datetime.time(0, 50)
 datetime.time(4, 10) datetime.time(3, 45) datetime.time(2, 35)
 datetime.time(18, 5) datetime.time(10, 29) datetime.time(11, 40)
 datetime.time(12, 9) datetime.time(17, 24) datetime.time(9, 58)
 datetime.time(5, 40) datetime.time(14, 44) datetime.time(23, 25)
 datetime.time(7, 16) datetime.time(9, 29) datetime.time(17, 15)
 datetime.time(16, 16) datetime.time(13, 35) datetime.time(4, 39)
 datetime.time(0, 35) datetime.time(10, 10) datetime.time(11, 22)
 datetime.time(15, 40) datetime.time(0, 43)]
[4 1 7 0 5 18 19 15 11 22 16 9 23 6 10 17 12 8 20 21 14 3 2 13]
0
0

# LUGAR_DEL_HECHO, TIPO_DE_CALLE, Calle

In [147]:
hechos[['LUGAR_DEL_HECHO', "TIPO_DE_CALLE", "Calle"]]

,LUGAR_DEL_HECHO,TIPO_DE_CALLE,Calle
0,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,PIEDRA BUENA AV.
1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,"PAZ, GRAL. AV."
2,AV ENTRE RIOS 2034,AVENIDA,ENTRE RIOS AV.
3,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,LARRAZABAL AV.
4,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,SAN JUAN AV.
...,...,...,...
691,AV. RIESTRA Y MOM,AVENIDA,RIESTRA AV.
692,AU DELLEPIANE Y LACARRA,AUTOPISTA,"DELLEPIANE, LUIS, TTE. GRAL."
693,AV. GAONA Y TERRADA,AVENIDA,GAONA AV.
694,AV. EVA PERON 4071,AVENIDA,"PERON, EVA AV."
695,PADRE CARLOS MUJICA 709,CALLE,PADRE CARLOS MUJICA

In [148]:
print(hechos['LUGAR_DEL_HECHO'].unique())

['AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ'
 'AV GRAL PAZ  Y AV DE LOS CORRALES' 'AV ENTRE RIOS 2034'
 'AV LARRAZABAL Y GRAL VILLEGAS CONRADO'
 'AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA '
 'AV 27 DE FEBRERO Y AV ESCALADA' 'NOGOYA Y JOAQUIN V. GONZALES'
 'AV GENERAL PAZ Y AV DE LOS CORRALES'
 'AV BELGRANO Y BERNARDO DE IRIGOYEN' 'AV ENTRE RIOS 1366'
 'AV SCALABRINI ORTIZ Y VERA'
 'AV REGIMIENTO DE PATRICIOS Y QUINQUELA MARTIN BENITO'
 'MARIANO ACOSTA Y ANA MARIA JANER'
 'LISANDRO DE LA TORRE Y SEVERO GARCIA GRANDE DE ZEQUEIRA ' 'SUIPACHA 156'
 'AV DIRECTORIO Y CURAPALIGUE' 'AV 9 DE JULIO Y ADOLFO ALSINA'
 'AV GRAL PAZ Y AV 27 DE FEBRERO' 'HOLMBERG Y VEDIA'
 'CURAPALIGUE Y AVELINO DIAZ' 'VIAMONTE Y AV 9 DE JULIO'
 'AV CABILDO Y DEHEZA' 'AV GRAL PAZ Y AV CNEL ROCA'
 'AV AMANCIO ALCORTA Y BONAVENA' 'AV CORRIENTES Y AV CALLAO'
 'HERRERA Y ARISTOBULO DEL VALLE' 'AV. EVA PERON Y QUIRNO'
 'AV GRAL PAZ COLECTORA Y ZUVIRIA' 'BARTOLOME MITRE Y AV PUEYRREDON'
 'AV DIRECTORIO Y RIVERA INDARTE'
 'DELLEPIANE LUIS TTE GRAL COLECTORA Y MURGUIONDO'
 'AV JOSE MARIA MORENO Y BALBASTRO' 'AV GRAL PAZ Y AV DEL LIBERTADOR'
 'LIMA 1483' 'AV. CORRIENTES Y AV. DORREGO'
 'AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI KM. 0,700'
 'TIMOTEO GORDILLO Y AV FERNANDEZ DE LA CRUZ' 'AUTOPISTA LUGONES PK 10000'
 'AV TRIUNVIRATO Y AV OLAZABAL' 'AU LUIS DELLEPIANE Y AV GRAL PAZ'
 'RAMON CASTILLA Y AV FIGUEROA ALCORTA' 'AV LUIS MARIA CAMPOS 30'
 'LIMA 1471' 'PASAJE CIUDADELA Y LIMA OESTE'
 'AV JUAN B JUSTO Y AV CARRASCO' 'AV GAONA Y ESPINOSA'
 'AV LISANDRO DE LA TORRE Y SARAZA' 'AV FIGUEROA ALCORTA Y AV PUEYRREDON'
 'AV ENTRE RIOS Y PASAJE FILIBERTO' 'MAGARIÑOS CERVANTES 3900'
 'AV GRAL PAZ Y RODOLFO SCAPINO'
 'AUTOPISTA DELLEPIANE LUIS TTE GRAL Y MIRALLA'
 'AV SAN MARTIN Y CAMARONES' 'TTEG JUAN D PERON Y AVDA LEANDRO N ALEM'
 'AV BELGRANO Y AV JUJUY' 'AV DEL LIBERTADOR Y AV GUILLERMO UDAONDO'
 'AV GRAL PAZ Y AV RIVADAVIA' 'AV CRISOLOGO LARRALDE Y MACHAIN'
 'AV LA PLATA 2384' 'AV JUAN B ALBERDI Y PUAN'
 'CARLOS PELLEGRINI Y TUCUMAN'
 'AVDA ITE FRANCISCO RABANAL & AVDA EREZCANO' 'AV OLIVERA Y RAMON FALCON'
 'AUTOPISTA 1 SUR PTE ARTURO FRONDIZI Y AV CASEROS' 'CERETTI Y NUÑEZ'
 'AV LUGONES Y LA PAMPA' 'JERONIMO SALGUERO Y AV RIVADAVIA'
 'AV GRAL PAZ Y AV LIBERTADOR ' 'AV JUAN B ALBERDI Y EMILIO MITRE'
 'MERCEDES Y AV GRAL MOSCONI'
 'AUTOPISTA DELLEPIANE LUIS TTE. GRAL. KM. 2,3' 'SOLIS Y MEXICO'
 'AV SAN JUAN Y ALBERTI' 'AV GRAL MOSCONI Y AV GRAL PAZ'
 'AV GRAL PAZ  Y DONADO' 'AV GRAL PAZ Y JORGE CHAVEZ'
 'AV EVA PERON Y JOSE LEON SUAREZ' 'ZINNY Y AV SANTIAGO DE COMPOSTELA'
 'AV FEDERICO LACROZE Y FRAGA' 'CARLOS PELLEGRINI Y AV DEL LIBERTADOR'
 'AUTOPISTA 9 DE JULIO SUR ALT AV MENDOZA'
 'AUTOPISTA PERITO MORENO Y BARRAGAN' 'AV ALBERDI Y CARHUE'
 'AUTOPISTA LEOPOLDO LUGONES Y LA PAMPA'
 'AUTOPISTA 25 DE MAYO AUTOPISTA 1 SUR ARTURO FRONDIZI'
 'AV JUAN BAUTISTA ALBERDI Y GUARDIA NACIONAL' 'SALGUERO 1410'
 'ARIAS Y TRONADOR' 'AV DEL LIBERTADOR Y TAGLE'
 'AUTOPISTA 1 SUR PTE ARTURO FRONDIZI KM 2.9'
 'CRISOLOGO LARRALDE Y AVDA TRIUNVIRATO' 'AV EVA PERON 4233'
 'AV ASAMBLEA Y AV CNEL ESTEBAN BONORINO'
 'AVDA RIVADAVIA Y RIVERA INDARTE'
 'AUTOPISTA PERITO MORENO Y AV JUAN B ALBERDI' 'IRIGOYEN Y TINOGASTA'
 'AV MARIANO ACOSTA Y AV CNEL ROCA' 'CASTRO Y AV PAVON'
 'AUTOPISTA 9 DE JULIO SUR Y AV BRASIL' 'MIRAVE 3500'
 'AV SAN JUAN Y 24 DE NOVIEMBRE' 'AV LAS HERAS Y SANCHEZ DE BUSTAMANTE'
 'AV PIEDRA BUENA Y 2 DE ABRIL 1982' 'AV FIGUEROA ALCORTA  Y PINEDO'
 'AU BUENOS AIRES - LA PLATA KM. 4' 'AV SAN MARTIN Y LADINES'
 'AV CABILDO Y BLANCO ENCALADA'
 'AV PRESIDENTE FIGUEROA ALCORTA Y AV DORREGO'
 'AV JURAMENTO Y VUELTA DE OBLIGADO' 'AV DEL LIBERTADOR Y AV RAMOS MEJIA'
 'AV. ALTE. BROWN 984' 'AV DEL LIBERTADOR Y LA PAMPA'
 'PICHINCHA Y AV BRASIL' 'AV INDEPENDENCIA Y VIRREY CEVALLOS'
 'AV GARMENDIA 4895' 'AV AMANCIO ALCORTA Y DIOGENES TABORDA' 'SD'
 'AV PERITO MORENO Y ZUVIRIA' 'ARAOZ Y AV CORDOBA' 'AV GRAL PAZ 15200'
 'MADERO 900' 'AV INDEPENDENCIA Y DEAN FUNES' 'AV JUAN B JUSTO 5645'
 'AUTOPISTA PERITO MORENO ALTURA VELZ' 'AV SANTA FE Y GODOY CRUZ'
 'AV FEDERICO LACROZE Y AV FOREST' 'AV GRAL PAZ Y AV GENERAL MOSCONI'
 'AV LA PLATA Y CNEL GREGORIO POMAR' 'AV MARTIN GARCIA 300'
 'NUÑEZ Y AV RICARDO BALBIN' 'AV GRAL PAZ 4500'
 'AU BUENOS AIRES - LA PLATA Y AU 25 DE MAYO' 'AV GARAY Y CASTRO'
 'AV DIRECTORIO Y AV SAN PEDRITO' 'AUTOPISTA 25 DE MAYO'
 'CNEL RAMON L FALCON Y MEMBRILLAR' 'AV BELGRANO Y AV PASEO COLON'
 'ARENALES 3319' 'REPUBLICA BOLIVARIANA DE VENEZUELA Y SAAVEDRA'
 'AV. JUAN B JUSTO Y ACHUPALLAS' 'OLAVARRIA Y AV. VELEZ SARSFIELD'
 'LIMA Y MEXICO' 'JOSE A CABRERA Y BONPLAND' 'AU 25 DE MAYO Y AV. BOEDO'
 'AV. DIRECTORIO Y RIGLOS' 'AV. GRAL. PAZ Y AV. R. BALBIN'
 'TRAFUL Y DIOGENES TABORDA' 'IRIARTE 3055' 'AV. DONADO Y ARIAS'
 'CORDOBA AV. Y CALLAO'
 'AU 25 DE MAYO, KILOMETRO 8.3, SENTIDO HACIA PROVINCIA DE BUENOS AIRES, C.A.B.A.'
 'AV. JUAN B JUSTO Y PARAGUAY' 'AV. GRAL. PAZ Y AV. DE LOS CORRALES'
 'SARMIENTO Y LIBERTAD' 'AV. RIVADAVIA 7121'
 'AV. FERNANDEZ DE LA CRUZ Y RIVERA INDARTE'
 'AV. PERITO MORENO Y FOURNIER' 'AV. CASEROS 1429'
 'AV. GAONA Y FRAGATA SARMIENTO' 'MOZART Y TANDIL'
 'MOZART Y COLECTORA AV. TTE. LUIS J DELLEPIANE'
 '24 DE NOVIEMBRE Y PAVON ' 'AV. GRAL. PAZ Y PEDRO DE MENDOZA'
 'AV. GRAL. PAZ KM. 10' 'GODOY CRUZ 2651'
 'AV. DR. TRISTAN ACHAVAL RODRIGUEZ Y BLVD. AZUCENA VILLAFLOR'
 'CURUPAYTI Y COLECTORA AV. GRAL. PAZ'
 'AV. INDEPENDENCIA Y VIRREY CEVALLOS' 'AV. CASTAÑARES Y LAUTARO'
 'CAMINO CIUDAD UNUVERSITARIA Y AV. TTE. GUIRALDES'
 'BALDOMERO FERNANDEZ MORENO 2186' 'AV. LEOPOLDO LUGONES PKM 6900'
 'NOGOYA 5940' 'AV. ARGENTINA Y AV. CORVALAN'
 'AV. FERNANDEZ DE LA CRUZ Y VARELA'
 'AU PERITO MORENO Y RAMAL ENLACE AU1/AU6' 'AU DELLEPIANE 2400'
 'AV. GRAL. PAZ Y GOLETA JULIA' 'VIEYTES Y VILLARINO'
 'AV. DE LOS CONSTITUYENTES Y PEDRO MORAN'
 'AV. DE LOS CONSTITUYENTES 4900' 'AV. CORDOBA Y LIBERTAD' 'BRASIL Y LIMA'
 'AV. ESCALADA Y AV. FERNANDEZ DE LA CRUZ' 'PARAGUAY Y AV. CALLAO '
 'AV. JUAN B JUSTO Y SAN BLAS' 'CHILE Y AV. 9 DE JULIO' 'MAIPU Y PERON'
 'AV. SUAREZ Y HERRERA' 'AV. SAN MARTIN Y FRAGATA SARMIENTO'
 'AV. DIRECTORIO Y AV. JOSE MARIA MORENO'
 'AV. TTE. FRANCISCO RABANAL 2950' 'AV. GRAL. PAZ Y ULRICO SCHMIDL'
 'NUEVA YORK  3696' 'AV. DE LOS CONSTITUYENTES Y VALLEJOS'
 'AV. CORRIENTES Y ECUADOR' 'CASCO 133' 'AV. DE MAYO Y AV. 9 DE JULIO'
 'AV. RAMON CASTILLO Y CALLE 12' 'FRAY JUSTO SANTAMARIA DE ORO 1930'
 'MEXICO Y DEAN FUNES' 'AV. JUAN B ALBERDI Y AV. ESCALADA'
 'AV. ENTRE RIOS Y AV. BRASIL' 'AV. JUAN B ALBERDI Y GUARDIA NACIONAL'
 'AV. DEL LIBERTADOR Y RODRIGUEZ PEÑA' 'TACUARI Y AV. MARTIN GARCIA'
 'AV. RIVADAVIA Y MURGUIONDO' '24 DE NOVIEMBRE 390'
 'AV. PASEO COLON Y BRASIL' 'MARTINIANO LEGUIZAMON 901'
 'AV. CHIVILCOY Y COLECTORA AV. GRAL. PAZ ' 'SUPERI Y AV. GRAL. PAZ'
 'AU 25 DE MAYO Y AU FRONDIZI (9 DE JULIO SUR)'
 'AV. LEOPOLDO LUGONES KM 7,5, ALTURA PUENTE SCALABRINI ORTIZ, SENTIDO A CENTRO PORTEÑO'
 'VICTOR HUGO 2639' 'AV. CORDOBA Y JERONIMO SALGUERO'
 'AV. CABILDO Y NUÑEZ' 'JOSE BONIFACIO 2114'
 'AV. PTE FIGUEROA ALCORTA 5400' 'VENEZUELA 2135'
 'AV. FCO. LACROZE Y ZAPATA' 'IRIARTE Y ZAVALETA'
 'AV. 9 DE JULIO Y ESTADOS UNIDOS' 'FRAY JUSTO SANTAMARIA DE ORO Y GUEMES'
 'AV. DEL LIBERTADOR Y JARAMILLO' 'AV. GRAL. PAZ Y MACHAIN'
 'AV. DIRECTORIO Y PORTELA' 'LAVALLE Y AV. LEANDRO N ALEM'
 'USPALLATA Y PIROVANO' 'AU 25 DE MAYO Y AV. VARELA'
 'AV. SANTA FE Y MAIPU' 'AV. ALVEAR Y AV. DEL LIBERTADOR'
 'AV. PAVON Y TREINTA Y TRES ORIENTALES' 'COLECTORA AV. GRAL. PAZ 5750'
 'VIEYTES Y CRUZ' 'AU DELLEPIANE Y AV. ESCALADA'
 'ALBARIÑO Y AV. ARGENTINA' 'JUAN RAMIREZ DE VELAZCO 1211'
 'AV. FERNANDEZ DE LA CRUZ Y LARRAYA' 'AV. RIESTRA Y CAÑADA DE GOMEZ'
 'GALLO Y AV. CORDOBA' 'DR. JUAN F. ARANGUREN 611'
 'AU PERITO MORENO Y AU 25 DE MAYO' 'CHORROARIN Y AV. SAN MARTIN'
 'COSQUIN Y AV. CNEL. ROCA' 'AV. CNEL. ROCA 3555'
 'AV. WARNES Y PUNTA ARENAS' 'DEL BARCO CENTENERA Y RABANAL'
 'AV. GRAL. ENRIQUE MOSCONI Y SAN NICOLAS' 'AV. LAFUENTE Y AV. EVA PERON'
 'AV. CNEL. ROCA Y AV. ESCALADA' 'AU ARTURO FRONDIZI PKM 3100'
 'AV. LA PLATA Y AV. PEDRO GOYENA' 'TRELLES Y GRAL. CESAR DIAZ'
 'AV. CNEL. ROCA Y COLECTORA AV. GRAL. PAZ' 'MAZA Y DON BOSCO'
 'AV. GRAL. PAZ Y AV. EVA PERON' 'AV. SAN JUAN Y LA RIOJA'
 'AV. PASEO COLON Y MEXICO' 'AV. RIVADAVIA Y MIRALLA' 'VIEYTES Y LUJAN'
 'CACHI Y TRAFUL' 'ROSARIO Y AV. LA PLATA' 'AV. ENTRE RIOS Y AV. CASEROS '
 'AV. RIVADAVIA 6350' 'AV. GRAL. PAZ Y HUMAITA'
 'GUALEGUAYCHU Y COLECTORA AV. GRAL PAZ' 'AV. NAZCA 365'
 'AV. EVA PERON 5249' 'San Juan Av. Y Rincón' 'Peru 937'
 'Pueyrredon, Honorio, Dr. Av. y Galicia'
 'Del Libertador Av. y Manzanares' 'Paseo Colon Av. 1019'
 'Valle y Barco Centenera Del' 'AU Perito Moreno  KM 0.6'
 'Huergo, Ing. Av. e Independencia Av.' 'Pilcomayo y Brown, Alte. Av.'
 'Cervantes y Belaustegui, Luis, Dr.' 'Callao y Vte. Lopez'
 'Oliden y Chilavert, Martiniano, Coronel' 'Congreso Av. y Galvan'
 'Moreno, Perito Av. y Rivera Indarte' 'Australia Av. 2800'
 'Del Libertador Av. y Ramos Mejia, Jose Maria, Dr. Av.'
 'San Pedrito Av. y Rivadavia Av.'
 'Isabel La Catolica y Salvadores, Cnel.'
 'Las Heras General Av. y Callao Av.'
 'Fernandez de la Cruz Subida AU Héctor J. Cámpora'
 'AMANCIO ALCORTA Y ZAVALETA' 'Montes De Oca, Manuel y Olavarria'
 'Barco Centenera Del y Rosario' 'Alvarez Thomas Av. y Donado'
 'Av. Avellaneda y Av. Boyacá'
 'Rabanal, Francisco, Intendente Av. y Saenz Av.' 'Castro y Rondeau'
 'Bilbao, Francisco Av. y Azul' 'Nazca Av. y Gaona Av.'
 'Plaza y Alvarez Thomas Av.' 'Gaona Av. y Artigas, Jose Gervasio, Gral.'
 'Cabildo Av. y Aguilar' 'Camarones y Lope De Vega Av.'
 'Santa Fe Av. 2320' 'Av. Rivadavia 6950' 'Av. San Martín y Argerich'
 'Cordoba Av. y Uriburu Jose E., Pres.' 'AV. RIVADAVIA 1571'
 'AUTOPISTA LUGONES KM 4.7' 'Ramon Freire y Virrey Olaguer y Feliu'
 'La Plata Av. y Fernandez De La Cruz, F., Gral. Av.'
 'BRANDSEN y PERDRIEL' 'Vilardebo, Teodoro y Alvarez Jonte Av.'
 'Alberti e Independencia Av.' 'Alvarez Thomas Av. 879'
 'Av. Gral. Paz y Av. Rivadavia' 'Av. Corrientes y Av. Dorrego'
 'Rivadavia Av. y Pedernera' 'Quesada 2300' 'Cabildo Av. y Juramento Av.'
 'California y Carbonari, Francisco, Cmte.'
 'Carril, Salvador Maria Del Av. y Nazca' 'San Luis y Aguero'
 'Lugones 2430' 'Independencia Av. y Jujuy Av.' 'Av. Rivadavia 11050'
 'Combate De Los Pozos y Humberto 1°' 'Cordoba Av. y Thames'
 'Garay, Juan De Av. y Sanchez De Loria' 'Lavalle y Alem, Leandro N. Av.'
 'Estados Unidos y Pichincha' 'Rosario y Barco Centenera Del'
 'Av. Leandro N. Alem y Viamonte' 'Varela Av. y Primera Junta'
 'Pellegrini, Carlos y Juncal' 'Av. Corrientes y Av. Federico Lacroze'
 'Montes De Oca, Manuel y Finochietto Enrique Dr.'
 'Carabobo Av. y Alberdi, Juan Bautista Av.' 'Córdoba Av. 2215\n\n'
 'Estados Unidos y Urquiza, Gral.' 'Moreno y Av. Huergo'
 'AU Dellepiane kilometro 0.0, altura calle Montiel, sentido hacia el Centro Porteño'
 'Iriarte, Gral. Av. 3400' 'AV. JUAN B. ALBERDI 2968'
 'Del Libertador Av. y Ortiz De Ocampo' 'Chavez, Jorge y Paz, Gral. Av.'
 'Urquiza, Gral. y Estados Unidos' 'Paraguay y Sánchez De Bustamante'
 'De Los Corrales Av. y Paz, Gral. Av.'
 'Alberdi, Juan Bautista Av. y Carhue'
 'Castañares Av. y Rivera Indarte Av.'
 'Larrazabal y Garzon, Eugenio, Gral. Av.'
 'Paz, Gral. Av. y Fernandez De La Cruz, F., Gral. Av.'
 'Av. Alicia Moreau de Justo y Cochabamba'
 'Entre Rios Av. y Garay, Juan De Av.' 'Directorio Av. y Guardia Nacional'
 'Pavon Av. Y Colombres' 'Av. Gral. Paz y Av. Dr. Ricardo Balbín'
 'Pichincha Av. y Brasil' '27 De Febrero Av. y Pergamino'
 'AU Perito Moreno KM 1.8 ALTURA BARRAGAN SENTIDO PBA'
 'Cordoba Av. y Gascon' '15 De Noviembre De 1889 1513'
 'Salguero, Jeronimo y Beruti'
 'Lacarra Av. y Dellepiane, Luis, Tte. Gral.'
 'AU Héctor J. Cámpora y Roca, Cnel. Av.'
 'Av. Varela y Av. Int. Francisco Rabanal'
 'Av. Gral. Paz e/ Ferre y Beron de Astrada'
 'Elvira Rawson de Dellepiane 150' 'Paz, Gral. Av. y Zapiola'
 'FAMATINA Y DIOGENES TABORDA' 'Av. Castañares y Bonorino'
 'AU Frondizi 9 de Julio Sur y Av. Suarez' 'Nazca Av. y Rivadavia Av.'
 'Figueroa Alcorta, Pres. Av. y Echeverria' 'Rivadavia Av. y Jujuy Av.'
 'De Los Italianos Av. y Guemes, Macacha' 'Tucuman y Alem, Leandro N. Av.'
 'Corrientes Av. y Gallardo, Angel Av.'
 'AU Perito Moreno y Av. Eva Perón SENTIDO CENTRO' 'Muñecas y Serrano'
 'Artigas, Jose Gervasio, Gral. y Tres Arroyos'
 'Solis e Independencia Av.' 'Bosch, Ventura y Paz, Gral. Av.'
 'Paz, Gral. Av. 14800' 'Av. Eva Perón 5321'
 'Peron, Juan Domingo, Tte. General y Pueyrredon Av.'
 'Rabanal y San Pedrito' 'Monroe y Alvarez Thomas Av.'
 'Rivadavia Av. y Manzoni' 'AU Dellepiane Luis Tte. Gral. y Larrazabal'
 'Paz, Gral. Av. y Peron, Eva Av.'
 'AU Perito Moreno y Reservistas Argentinos' 'Saenz Av. y Ventana'
 'Avda. General Paz y Cnel. Ramón Falcón'
 'Av. Gral. Paz y Av. de los Constituyentes' 'Paz, Gral. Av. 11200'
 'Newbery, Jorge Av. y Guevara' 'Gaona Av. y Segurola Av.'
 'Madero, Eduardo Av. 550' 'AU Arturo Illia y Castillo, Ramon S.'
 'La Plata Av. y Caseros Av.' 'Belgrano Av. y Peru' 'Rivadavia Av. 7013'
 'Adolfo Alsina y Santiago del Estero' 'Bermudez 1893' 'Santander 1974'
 'Julieta Lanteri 1400' 'Maza y Av. Independencia' 'PAZ, GRAL. AV. 5172'
 'Olivera Av. y Alberdi, Juan Bautista Av.'
 'CASTILLO, RAMON S., PRES. AV. Y CALLE 12'
 'CASTAÑARES AV. Y MORENO, PERITO AV.' 'SAN MARTIN AV. Y TERRADA'
 'PERON, EVA AV. Y MEDINA' 'JUSTO, JUAN B. AV. Y ALVAREZ JONTE AV.'
 'OBLIGADO RAFAEL, AV. COSTANERA 4650' 'MITRE, BARTOLOME Y YATAY'
 'PAZ, GRAL. AV. 16080' 'CHACABUCO Y SAN JUAN AV.'
 'DEL LIBERTADOR AV. 4100' 'PAZ, GRAL. AV. Y ALBERDI, JUAN BAUTISTA AV.'
 'CASTAÑARES AV. Y GORDILLO, TIMOTEO' 'SALVIGNY Y MOM'
 'LAMARCA, EMILIO 5402' 'SAN MARTIN AV. 5638'
 'CARRILLO, RAMON, DR. Y FINOCHIETTO ENRIQUE DR.' 'MEXICO Y PICHINCHA'
 'CANTILO, INT. Y UDAONDO, GUILLERMO AV.' 'DEL LIBERTADOR AV. 6326'
 'CHICLANA AV. 3444' 'BOYACA AV. Y YERBAL'
 'PAZ, GRAL. AV. Y JACQUES, AMADEO'
 'MITRE, BARTOLOME Y SANCHEZ DE BUSTAMANTE'
 'FERNANDEZ DE LA CRUZ, F. , GRAL. AV. Y LARRAZABAL'
 'SANTA FE AV. Y AZCUENAGA' 'JUSTO, JUAN B. AV. y OROÑO, NICASIO'
 'FERNANDEZ DE LA CRUZ, F. , GRAL. AV. Y LACARRA AV.'
 'ALVAREZ, DONATO, TTE. GRAL. Y YERBAL'
 'CORDOBA AV. Y MADERO, EDUARDO AV.'
 'CAMARONES Y ALVAREZ, DONATO, TTE. GRAL. AV.'
 'AUTOPISTA 25 DE MAYO Y HUERGO, ING. AV.' 'MORENO, PERITO AV. 3050'
 'SUIPACHA 665' 'RIGLOS Y FORMOSA' 'LA RIOJA E INDEPENDENCIA AV.'
 'UDAONDO, GUILLERMO AV. Y FIGUEROA ALCORTA, PRES. AV.'
 'SAN PEDRITO AV. Y DIRECTORIO AV.' 'PUAN Y SANTANDER'
 'ALBERDI, JUAN BAUTISTA AV. Y ANDALGALA' 'LIMA Y CONSTITUCION'
 'BOEDO AV. 650' 'DEL LIBERTADOR AV. Y REPUBLICA DE LA INDIA'
 'GRAL PAZ Y CABILDO' 'CASEROS AV. 1700' 'AVELLANEDA AV. 1548'
 'CIUDAD DE LA PAZ Y MENDOZA' 'SALGUERO, JERONIMO Y HONDURAS AV.'
 'FILIBERTO, JUAN DE DIOS Y OLAVARRIA' 'ASTURIAS AV. Y CASTAÑARES AV.'
 'GANDARA 2976' 'GUEVARA, TRINIDAD Y MADERO, EDUARDO AV.' 'BOYACA AV. 305'
 'ARTILLEROS Y LA PAMPA'
 'AUTOPISTA PERITO MORENO ALTURA PASO A NIVEL DE IRIGOYEN'
 '15 DE NOVIEMBRE DE 1889 Y SANTIAGO DEL ESTERO'
 'ACOSTA, MARIANO AV. Y FALCON, RAMON L., CNEL.'
 '11 DE SEPTIEMBRE DE 1888 Y MENDOZA'
 'PINO, VIRREY DEL Y CAMPOS, LUIS M. AV.' 'FOREST AV. Y MAURE'
 'BOYACA AV. Y AVELLANEDA AV,' 'BARCO CENTENERA DEL Y TILCARA'
 'RIESTRA AV. Y BOLIVAR' 'CASTRO, EMILIO 4706' '27 DE FEBRERO AV. 5600'
 'GARAY, JUAN DE AV. 2874' 'SCALABRINI ORTIZ, RAUL AV. y GORRITI'
 'PRIMERA JUNTA Y OLIVERA AV.' 'ALBERDI, JUAN BAUTISTA AV. Y AZUL'
 'ALVAREZ THOMAS AV. 1788' 'LUGONES, LEOPOLDO AV. Y PAZ, GRAL. AV.'
 'SAN ANTONIO Y LUJAN'
 'AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI ALTURA DON PEDRO DE MENDOZA AV.'
 'FIGUEROA ALCORTA, PRES. AV. Y TAGLE'
 'EINSTEIN, ALBERTO Y ALCORTA, AMANCIO AV.' 'AGRELO Y COLOMBRES'
 'ELCANO AV. 4300' 'RABANAL, FRANCISCO, INTENDENTE AV. 2428'
 'MONTE Y CORVALAN' 'TANDIL Y LA FUENTE' 'CARDOSO Y BACACAY'
 'CORRIENTES AV. 6700' 'ALVAREZ THOMAS AV. Y MENDOZA'
 'ALCORTA, AMANCIO AV. Y BONAVENA, OSCAR NATALIO'
 'BROWN, ALTE. AV. Y BLANES, JUAN MANUEL'
 'ALBERDI, JUAN BAUTISTA AV. 5455' 'JUSTO, JUAN B. AV. Y CAMARGO'
 'BRIN, MINISTRO Y SUAREZ' 'NIZA Y JUSTO, JUAN B. AV.' 'CAMARGO Y SERRANO'
 'AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI ALTURA CASEROS AV.'
 'CASEROS AV. Y PIEDRAS' 'AUTOPISTA PERITO MORENO KM 5,6' 'GUZMAN 365'
 'de los constituyentes av. 4300' 'MORENO, PERITO AV. Y TILCARA AV.'
 'IBARROLA Y GORDILLO, TIMOTEO' 'RIVADAVIA AV. Y PERGAMINO'
 'SANTO TOME Y SEGUROLA AV.' 'URIARTE Y LOYOLA' 'SARAZA Y VARELA AV.'
 'RIVADAVIA AV. Y COMBATE DE LOS POZOS' 'RODRIGUEZ PEÑA Y RIVADAVIA AV.'
 '24 DE NOVIEMBRE Y SAN JUAN AV.' 'LAFUENTE AV. 2250' 'CHILE Y LIMA '
 'CORDOBA AV. Y JEAN JAURES'
 'PERON, JUAN DOMINGO, TTE. GENERAL Y SALGUERO, JERONIMO'
 '9 DE JULIO AV. Y SAN JUAN AV.' 'COLOMBRES 466' 'MEXICO 2860'
 'COMBATIENTES DE MALVINAS AV. Y TRIUNVITARO AV.' 'BERMUDEZ Y NOGOYA'
 'BRASIL AV. Y PASEO COLON AV.' 'ALEM,LEANDRO N. AV. 770'
 'BELGRANO AV. Y RINCON' 'UDAONDO, GUILLERMO AV. 901'
 'CONSTITUCION Y CASTRO' 'PUEYRREDON AV. Y GOMEZ, VALENTIN'
 'BRAVO, MARIO 1279' 'DELLEPIANE, LUIS, TTE. GRAL. Y ESCALADA AV.'
 'ARAOZ DE LAMADRID, GREGORIO, GRAL. Y BROWN, ALTE. AV.' 'MURGUIONDO 1339'
 'RIVADAVIA AV. 2551' 'LUGONES, LEOPOLDO AV. KM 6,1'
 'DELLEPIANE, LUIS, TTE. GRAL. Y MONTIEL'
 'SCALABRINI ORTIZ, RAUL AV. Y WARNES AV.'
 'PAZ, GRAL. AV. y ROFFO, ANGEL H., DR.' 'SAN MARTIN AV. 1550'
 'GARZON, EUGENIO, GRAL. AV. y LARRAYA' 'CORRIENTES AV. Y SERRANO'
 'PAZ, GRAL. AV. Y DEL LIBERTADOR AV.'
 'MITRE, BARTOLOME Y ANCHORENA, TOMAS MANUEL DE, DR.'
 'AU 25 DE MAYO ALTURA PUMACAHUA Y RECUERO, CASIMIRO, TTE. CNEL.'
 'SCALABRINI ORTIZ, RAUL AV. Y PARAGUAY'
 'FERNANDEZ DE LA CRUZ, F., GRAL. AV. Y VARELA AV.'
 'LAS HERAS GENERAL AV. Y DIAZ, CNEL. AV.' 'MURGUIONDO 2700'
 'CURAPALIGUE Y PERON, EVA AV.' 'DIAZ, ANA Y SOLDADO DE LA FRONTERA AV.'
 'ALEM, LEANDRO N. AV. Y PARAGUAY' 'LA PLATA AV. E INDEPENDENCIA'
 'PAZ, GRAL. AV. Y 27 DE FEBRERO AV.' 'NAZCA AV. Y CARRANZA, ADOLFO P.'
 'AUTOPISTA CAMPORA ALTURA LACARRA AV.' 'DORREGO AV. 614'
 'DEL LIBERTADOR AV. Y RAMOS MEJIA, JOSE MARIA, DR. AV.'
 'SANTA FE AV. Y GODOY CRUZ' 'AVELLANEDA AV. Y MERCEDES'
 'TUCUMAN Y PUEYRREDON AV.' 'ALCORTA, AMANCIO AV. Y EINSTEIN, ALBERTO'
 'INCLAN Y ALBERTI' 'OLAZABAL AV. 5437'
 'PAZ, GRAL. AV. Y DOCTOR RAMON CARRILLO' 'NAZCA AV. Y VIALE, LUIS'
 'OLIVERA AV. Y FALCON, RAMON L., CNEL.' 'BRASIL 1100'
 'HOMERO Y PERON, EVA AV.' 'MORENO 1845' 'NUEVA YORK Y ALTA GRACIA'
 'PAZ, GRAL. AV. Y GOYENECHE, ROBERTO PARQUE AV.'
 'AUTOPISTA PERITO MORENO ALTURA ESTACION DE TREN VILLA LURO'
 'SAENZ AV. Y BEAZLEY' 'DEL LIBERTADOR AV. Y AUSTRIA'
 'INDEPENDENCIA AV. Y SAENZ PEÑA, LUIS, PRES.'
 'CALLAO AV. Y LAS HERAS, GENERAL' 'JUJUY AV. Y CARLOS, CALVO'
 '27 DE FEBRERO AV. Y ESCALADA AV.' 'BOGOTA Y NAZCA AV.'
 'CORRIENTES AV. Y 9 DE JULIO AV.' 'ALVAREZ JONTE AV. Y CHIVILCOY'
 'SAN MARTIN AV. Y PUNTA ARENAS' 'BARCO CENTENERA DEL 1118'
 'PAZ, GRAL. AV. Y ACCESO NORTE - PANAMERICANA' 'AU FRONDIZI KM. 3'
 'CASTRO, EMILIO AV. Y MURGUIONDO' 'AU 25 DE MAYO KM. 3,7'
 'CASEROS AV. Y GUARANI' 'PERON, EVA AV. 3800' 'AU ILLIA y SARMIENTO AV.'
 'DE LOS CONSTITUYENTES AV. Y GIRIBONE'
 'SAENZ AV. Y RABANAL, FRANCISCO, INTENDENTE AV.' 'PAYSANDU Y GAONA'
 'PAZ, GRAL. AV. Y BALBIN, RICARDO, DR. AV. ' 'SANTA FE AV. 1675'
 'AU DELLEPIANE Y GUAMINI' 'FALCON, RAMON L., CNEL. Y OLIVERA AV.'
 'SAN MARTIN AV. Y NOGOYA' 'SAN MARTIN AV. Y TINOGASTA'
 'FERNANDEZ DE LA CRUZ, F., GRAL. AV. Y DE LA TORRE, LISANDRO'
 'SALTA Y CASEROS AV.' 'JAURES, JEAN Y PERON, JUAN DOMINGO, TTE. GENERAL'
 'TRIUNVIRATO AV. Y LARRALDE, CRISOLOGO AV.' 'POTOSI Y GASCON'
 'YRIGOYEN, HIPOLITO Y  24 DE NOVIEMBRE'
 'DEL LIBERTADOR AV. Y ROOSEVELT FRANKLIN D.'
 'AU BUENOS AIRES LA PLATA  KM 4,5' 'PERON, EVA AV. y PIEDRA BUENA AV'
 'PAZ, GRAL. AV. y DELLEPIANE, LUIS, TTE. GRAL'
 'AU FRONDIZI ALTURA QUINQUELA MARTIN, BENITO' 'PAZ, GRAL. AV. y DONADO'
 'COREA AV. y TORRES Y TENORIO, PRES'
 'FALCON, RAMON L., CNEL. Y SAN PEDRITO AV.'
 'FINOCHIETTO ENRIQUE DR. 1623' '9 DE JULIO AV. E INDEPENDENCIA AV.'

In [149]:


print(hechos['TIPO_DE_CALLE'].unique())

['AVENIDA' 'GRAL PAZ' 'CALLE' 'AUTOPISTA']

In [150]:
print(hechos['Calle'].unique())

['PIEDRA BUENA AV.' 'PAZ, GRAL. AV.' 'ENTRE RIOS AV.' 'LARRAZABAL AV.'
 'SAN JUAN AV.' '27 DE FEBRERO AV.' 'NOGOYA' 'BELGRANO AV.'
 'SCALABRINI ORTIZ, RAUL AV.' 'REGIMIENTO DE PATRICIOS AV.'
 'ACOSTA, MARIANO' 'DE LA TORRE, LISANDRO' 'SUIPACHA' 'DIRECTORIO AV.'
 '9 DE JULIO AV.' 'HOLMBERG' 'CURAPALIGUE AV.' 'VIAMONTE' 'CABILDO AV.'
 'ALCORTA, AMANCIO AV.' 'CORRIENTES AV.' 'HERRERA' 'LAFUENTE AV.'
 'MITRE, BARTOLOME' 'DELLEPIANE, LUIS, TTE. GRAL.'
 'MORENO, JOSE MARIA AV.' 'LIMA'
 'AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI' 'GORDILLO, TIMOTEO'
 'LUGONES, LEOPOLDO AV.' 'TRIUNVIRATO AV.'
 'AUTOPISTA DELLEPIANE LUIS TTE. GRAL.' 'CASTILLA, RAMON, MARISCAL'
 'CAMPOS, LUIS M. AV.' 'CIUDADELA' 'JUSTO, JUAN B. AV.' 'GAONA AV.'
 'FIGUEROA ALCORTA, PRES. AV.' 'MAGARI?OS CERVANTES, A.' 'SAN MARTIN AV.'
 'PERON, JUAN DOMINGO, TTE. GENERAL' 'DEL LIBERTADOR AV.'
 'LARRALDE, CRISOLOGO AV.' 'LA PLATA AV.' 'ALBERDI, JUAN BAUTISTA AV.'
 'PELLEGRINI, CARLOS' 'RABANAL, FRANCISCO, INTENDENTE AV.' 'OLIVERA AV.'
 'CERETTI' 'SALGUERO, JERONIMO' 'MERCEDES' 'SOLIS' 'MOSCONI GENERAL AV.'
 'PERON, EVA AV.' 'ZINNY' 'LACROZE, FEDERICO AV.'
 'AUTOPISTA PERITO MORENO' 'LUGONES' 'AUTOPISTA 25 DE MAYO' 'ARIAS'
 'ASAMBLEA AV.' 'RIVADAVIA AV.' 'IRIGOYEN' 'CASTRO' 'MIRAVE'
 'LAS HERAS GENERAL AV.' 'AUTOPISTA BUENOS AIRES - LA PLATA'
 'JURAMENTO AV.' 'BROWN, ALTE. AV.' 'PICHINCHA AV.' 'INDEPENDENCIA AV.'
 'GARMENDIA AV.' nan 'MORENO, PERITO AV.' 'ARAOZ' 'MADERO' 'SANTA FE AV.'
 'GARCIA, MARTIN AV.' 'NU?EZ' 'HUERGO, ING. AV.' 'GARAY, JUAN DE AV.'
 'FALCON, RAMON L.,CNEL.' 'ARENALES' 'REPUBLICA BOLIVARIANA DE VENEZUELA'
 'OLAVARRIA' 'CABRERA, JOSE A.' 'TRAFUL' 'IRIARTE, GRAL. AV.' 'DONADO'
 'CORDOBA AV.' 'SARMIENTO' 'FERNANDEZ DE LA CRUZ, F., GRAL. AV.'
 'CASEROS AV.' 'MOZART' '24 DE NOVIEMBRE' 'GODOY CRUZ'
 'ACHAVAL RODRIGUEZ, T., DR. AV.' 'CASTA?ARES AV.' 'GUIRALDES, INT.'
 'FERNANDEZ MORENO, BALDOMERO' 'ARGENTINA AV.' 'VIEYTES'
 'DE LOS CONSTITUYENTES AV.' 'BRASIL' 'ESCALADA AV.' 'PARAGUAY' 'CHILE'
 'MAIPU' 'SUAREZ AV.' 'NUEVA YORK' 'CASCO' 'DE MAYO AV.'
 'CASTILLO, RAMON S., PRES. AV.' 'FRAY JUSTO SANTAMARIA DE ORO' 'MEXICO'
 'TACUARI' 'PASEO COLON AV.' 'LEGUIZAMON, MARTINIANO' 'CHIVILCOY AV.'
 'SUPERI' 'HUGO, VICTOR' 'BONIFACIO, JOSE' 'LAVALLE' 'USPALLATA'
 'ALVEAR AV.' 'PAVON AV.' 'ALBARI?O' 'RAMIREZ DE VELASCO, JUAN'
 'RIESTRA AV.' 'GALLO' 'ARANGUREN, JUAN F., DR.' 'CHORROARIN' 'COSQUIN'
 'ROCA, CNEL. AV.' 'WARNES AV.' 'BARCO CENTENERA DEL' 'TRELLES, MANUEL R.'
 'MAZA' 'CACHI' 'ROSARIO' 'GUALEGUAYCHU' 'NAZCA AV.' 'PERU'
 'PUEYRREDON, HONORIO, DR. AV.' 'VALLE' 'PILCOMAYO' 'CERVANTES'
 'CALLAO AV.' 'OLIDEN' 'CONGRESO AV.' 'AUSTRALIA AV.' 'SAN PEDRITO AV.'
 'ISABEL LA CATOLICA' 'AUTOPISTA PRESIDENTE HECTOR J. CAMPORA'
 'MONTES DE OCA, MANUEL AV.' 'ALVAREZ THOMAS AV.' 'AVELLANEDA AV.'
 'BILBAO, FRANCISCO AV.' 'PLAZA' 'CAMARONES' 'FREIRE, RAMON, CAP. GRAL.'
 'BRANDSEN' 'VILARDEBO, TEODORO' 'ALBERTI' 'QUESADA' 'CALIFORNIA'
 'CARRIL, SALVADOR MARIA DEL AV.' 'SAN LUIS' 'COMBATE DE LOS POZOS'
 'ESTADOS UNIDOS' 'ALEM, LEANDRO N. AV.' 'VARELA AV.' 'CARABOBO AV.'
 'MORENO' 'CHAVEZ, JORGE' 'URQUIZA, GRAL.' 'DE LOS CORRALES AV.'
 'CASTANARES AV.' 'LARRAZABAL' 'MOREAU DE JUSTO, ALICIA AV.'
 '15 DE NOVIEMBRE DE 1889' 'LACARRA AV.'
 'AUTOPISTA PRESIDENTE H?CTOR J. C?MPORA'
 'RAWSON DE DELLEPIANE, ELVIRA AV.' 'FAMATINA' 'DE LOS ITALIANOS AV.'
 'TUCUMAN' 'MU?ECAS' 'ARTIGAS, JOSE GERVASIO, GRAL.' 'BOSCH, VENTURA'
 'MONROE' 'SAENZ AV.' 'NEWBERY, JORGE AV.' 'MADERO, EDUARDO AV.'
 'AUTOPISTA ARTURO ILLIA' 'ALSINA, ADOLFO' 'BERMUDEZ' 'SANTANDER'
 'LANTERI JULIETA' 'OBLIGADO RAFAEL, AV.COSTANERA' 'CHACABUCO' 'SALVIGNY'
 'LAMARCA, EMILIO' 'CARRILLO, RAMON, DR.' 'CANTILO, INT.' 'CHICLANA AV.'
 'BOYACA AV.' 'ALVAREZ, DONATO, TTE. GRAL.' 'RIGLOS' 'LA RIOJA'
 'UDAONDO, GUILLERMO AV.' 'PUAN' 'BOEDO AV.' 'CIUDAD DE LA PAZ'
 'FILIBERTO, JUAN DE DIOS' 'ASTURIAS AV.' 'GANDARA' 'GUEVARA, TRINIDAD'
 'ARTILLEROS' 'ACOSTA, MARIANO AV.' '11 DE SEPTIEMBRE DE 1888'
 'PINO, VIRREY DEL' 'FOREST AV.' 'CASTRO, EMILIO' 'PRIMERA JUNTA'
 'SAN ANTONIO' 'EINSTEIN, ALBERTO' 'AGRELO' 'ELCANO AV.' 'MONTE' 'TANDIL'
 'CARDOSO' 'BRIN, MINISTRO' 'NIZA' 'CAMARGO' 'GUZMAN' 'IBARROLA'
 'SANTO TOME' 'URIARTE' 'SARAZA' 'RODRIGUEZ PE?A' 'COLOMBRES'
 'COMBATIENTES DE MALVINAS AV.' 'BRASIL AV.' 'CONSTITUCION'
 'PUEYRREDON AV.' 'BRAVO, MARIO' 'ARAOZ DE LAMADRID, GREGORIO, GRAL.'
 'MURGUIONDO' 'GARZON, EUGENIO, GRAL. AV.' 'CURAPALIGUE' 'DIAZ, ANA'
 'DORREGO AV.' 'INCLAN' 'OLAZABAL AV.' 'HOMERO' 'JUJUY AV.' 'BOGOTA'
 'ALVAREZ JONTE AV.' 'CASTRO, EMILIO AV.' 'PAYSANDU' 'SALTA'
 'JAURES, JEAN' 'POTOSI' 'YRIGOYEN, HIPOLITO' 'COREA AV.'
 'FINOCHIETTO ENRIQUE DR.' 'JANER, ANA MARIA' 'VEDIA, AGUSTIN DE'
 'CAPDEVILA' 'TABARE' 'CORRALES' 'LOPE DE VEGA AV.' 'BEIRO, FRANCISCO AV.'
 'CHILAVERT, MARTINIANO, CORONEL' 'TAPALQUE' 'ESMERALDA' 'BAIGORRIA'
 'PADRE CARLOS MUJICA']

In [151]:
# Verificación de valores nulos

# Buscar registros igual a 'SD'

print(hechos[hechos['LUGAR_DEL_HECHO'] == 'SD'])
print(hechos[hechos['TIPO_DE_CALLE'] == 'SD'])
print(hechos[hechos['Calle'] == 'SD'])

# Verificar datos Na

print(hechos['LUGAR_DEL_HECHO'].isnull().sum())
print(hechos['TIPO_DE_CALLE'].isnull().sum())
print(hechos['Calle'].isnull().sum())

            ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
119  2016-0151           1 2016-11-18  2016  11  18  20:35:00  20

    LUGAR_DEL_HECHO TIPO_DE_CALLE  ... Altura  Cruce Dirección Normalizada  \
119              SD         CALLE  ...    NaN    NaN                   NaN

    COMUNA    XY (CABA) pos x pos y PARTICIPANTES VICTIMA ACUSADO
119      0  Point (. .)     .     .     PEATON-SD  PEATON      SD

[1 rows x 21 columns]
Empty DataFrame
Columns: [ID, N_VICTIMAS, FECHA, AAAA, MM, DD, HORA, HH, LUGAR_DEL_HECHO, TIPO_DE_CALLE, Calle, Altura, Cruce, Dirección Normalizada, COMUNA, XY (CABA), pos x, pos y, PARTICIPANTES, VICTIMA, ACUSADO]
Index: []

[0 rows x 21 columns]
Empty DataFrame
Columns: [ID, N_VICTIMAS, FECHA, AAAA, MM, DD, HORA, HH, LUGAR_DEL_HECHO, TIPO_DE_CALLE, Calle, Altura, Cruce, Dirección Normalizada, COMUNA, XY (CABA), pos x, pos y, PARTICIPANTES, VICTIMA, ACUSADO]
Index: []

[0 rows x 21 columns]
0
0
1

Las variables `LUGAR_DEL_HECHO`, `TIPO_DE_CALLE` y `Calle` contienen información sobre la ubicación de los incidentes y se encuentran acorde a la descripción, se detecto un valor 'SD' que se debera tratar.

In [152]:
hechos['LUGAR_DEL_HECHO'].replace('SD', pd.NA, inplace=True)
hechos.dropna(subset=['LUGAR_DEL_HECHO'], inplace=True)

# Altura, Cruce

In [153]:
print(hechos['Altura'].unique())
print(hechos['Altura'].isnull().sum())
print(hechos['Cruce'].unique())
print(hechos['Cruce'].isnull().sum())

[   nan  2034.  1366.   156.  1483.    30.  1471.  3900.  2384.  1410.
  4233.  3500.   984.  4895. 15200.   900.  5645.   300.  4500.  3319.
  3055.  7121.  1429.  2651.  2699.  2186.  5940.  4900.  2950.  3696.
   133.  1930.   390.   901.  2639.  2114.  5400.  2135.  5750.  1211.
   611.  3555.  6350.   365.  5249.   937.  1019.  2800.  2320.  6950.
  1571.   879.  2300.  2430. 11050.  2215.  3400.  2968.  1513.   150.
 14800.  5321. 11200.   550.  7013.  1893.  1974.  1400.  5172.  4650.
 16080.  4100.  5402.  5638.  6326.  3444.  3050.   665.   650.  1700.
  1548.  2976.   305.  4706.  5600.  2874.  1788.  4300.  2428.  6700.
  5455.  2250.   466.  2860.   770.  1279.  1339.  2551.  1550.   614.
  5437.  1100.  1845.  1118.  3800.  1675.  1623. 10900.  4000.  5958.
 14723.  5783.  2269.  2723.  2906.  5071.  3428.  2730.  2152.  1169.
  3112.  1359.  3655.  4071.   709.]
564
['FERNANDEZ DE LA CRUZ, F., GRAL. AV.' 'DE LOS CORRALES AV.' nan
 'VILLEGAS, CONRADO, GRAL.' 'SAENZ PE?A, LUIS, PRES.' 'ESCALADA AV.'
 'GONZALEZ, JOAQUIN V.' 'IRIGOYEN, BERNARDO DE' 'VERA'
 'QUINQUELA MARTIN, BENITO' 'JANER, ANA MARIA'
 'GARCIA GRANDE DE ZEQUEIRA, SEVERO' 'CURAPALIGUE' 'ALSINA, ADOLFO'
 '27 DE FEBRERO AV.' 'VEDIA' 'DIAZ, AVELINO' '9 DE JULIO AV.' 'DEHEZA'
 'ROCA, CNEL. AV.' 'BONAVENA, OSCAR NATALIO' 'CALLAO AV.'
 'VALLE, ARISTOBULO DEL' 'QUIRNO' 'ZUVIRIA' 'PUEYRREDON AV.'
 'RIVERA INDARTE AV.' 'MURGUIONDO' 'BALBASTRO' 'DEL LIBERTADOR AV.'
 'DORREGO AV.' 'OLAZABAL AV.' 'PAZ, GRAL. AV.'
 'FIGUEROA ALCORTA, PRES. AV.' 'LIMA' 'CARRASCO AV.' 'ESPINOSA' 'SARAZA'
 'FILIBERTO' 'SCAPINO, RODOLFO' 'MIRALLA' 'CAMARONES'
 'ALEM, LEANDRO N. AV.' 'JUJUY AV.' 'UDAONDO, GUILLERMO AV.'
 'RIVADAVIA AV.' 'MACHAIN' 'PUAN' 'TUCUMAN' 'EREZCANO'
 'FALCON, RAMON L.,CNEL.' 'NU?EZ' 'LA PAMPA' 'MITRE, EMILIO'
 'MOSCONI GENERAL AV.' 'MEXICO' 'ALBERTI' 'DONADO' 'CHAVEZ, JORGE'
 'SUAREZ, JOSE LEON' 'SANTIAGO DE COMPOSTELA AV.' 'FRAGA' 'BARRAGAN'
 'CARHUE' 'AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI' 'GUARDIA NACIONAL'
 'TRONADOR' 'TAGLE' 'TRIUNVIRATO AV.' 'BONORINO, ESTEBAN, CNEL. AV.'
 'ALBERDI, JUAN BAUTISTA AV.' 'TINOGASTA' 'PAVON AV.' '24 DE NOVIEMBRE'
 'SANCHEZ DE BUSTAMANTE' '2 DE ABRIL DE 1982' 'PINEDO, INT.' 'LADINES'
 'BLANCO ENCALADA' 'VUELTA DE OBLIGADO' 'RAMOS MEJIA, JOSE MARIA, DR. AV.'
 'BRASIL' 'CEVALLOS, VIRREY' 'TABORDA, DIOGENES' 'CORDOBA AV.'
 'DEAN FUNES' 'GODOY CRUZ' 'FOREST AV.' 'POMAR, GREGORIO TTE. CNEL.'
 'BALBIN, RICARDO, DR. AV.' 'AUTOPISTA 25 DE MAYO' 'CASTRO'
 'SAN PEDRITO AV.' 'MEMBRILLAR' 'PASEO COLON AV.' 'SAAVEDRA' 'ACHUPALLAS'
 'VELEZ SARSFIELD AV.' 'BONPLAND' 'RIGLOS' 'ARIAS' 'PARAGUAY' 'LIBERTAD'
 'FOURNIER' 'FRAGATA PRES. SARMIENTO' 'TANDIL'
 'AUTOPISTA DELLEPIANE LUIS TTE. GRAL.' 'PAVON' 'LOS CEDROS'
 'GUTIERREZ, RICARDO' 'VILLAFLOR, AZUCENA' 'CAMPANA' 'LAUTARO' 'CORVALAN'
 'VARELA AV.' 'GOLETA SANTA CRUZ' 'VILLARINO' 'MORAN, PEDRO' 'SAN BLAS'
 'PERON, JUAN DOMINGO, TTE. GENERAL' 'HERRERA' 'MORENO, JOSE MARIA AV.'
 'SCHMIDL, ULRICO' 'VALLEJOS' 'ECUADOR' 'CALLE 12 (NO OFICIAL)'
 'RODRIGUEZ PE?A' 'GARCIA, MARTIN AV.' 'BRASIL AV.'
 'PUENTE DISTRIBUIDOR SCALABRINI ORTIZ' 'SALGUERO, JERONIMO' 'ZAPATA'
 'ZAVALETA' 'ESTADOS UNIDOS' 'GUEMES' 'JARAMILLO' 'PORTELA' 'PIROVANO'
 'MAIPU' 'TREINTA Y TRES ORIENTALES' 'CRUZ, OSVALDO AV.' 'ARGENTINA AV.'
 'LARRAYA' 'CA?ADA DE GOMEZ' 'SAN MARTIN AV.' 'PUNTA ARENAS'
 'RABANAL, FRANCISCO, INTENDENTE AV.' 'SAN NICOLAS' 'PERON, EVA AV.'
 'GOYENA, PEDRO AV.' 'DIAZ, CESAR, GRAL.' 'DON BOSCO' 'LA RIOJA' 'LUJAN'
 'TRAFUL' 'LA PLATA AV.' 'CASEROS AV.' 'HUMAITA' 'RINCON' 'GALICIA'
 'MANZANARES' 'BARCO CENTENERA DEL' 'INDEPENDENCIA AV.' 'BROWN, ALTE. AV.'
 'BELAUSTEGUI, LUIS, DR.' 'LOPEZ, VICENTE'
 'CHILAVERT, MARTINIANO, CORONEL' 'GALVAN' 'SALVADORES, CNEL.' 'OLAVARRIA'
 'ROSARIO' 'BOYACA AV.' 'SAENZ AV.' 'RONDEAU' 'AZUL' 'GAONA AV.'
 'ALVAREZ THOMAS AV.' 'ARTIGAS, JOSE GERVASIO, GRAL.' 'AGUILAR'
 'LOPE DE VEGA AV.' 'ARGERICH' 'URIBURU JOSE E., PRES.'
 'OLAGUER Y FELIU, VIRREY' 'PERDRIEL' 'ALVAREZ JONTE AV.' 'PEDERNERA'
 'JURAMENTO AV.' 'CARBONARI, FRANCISCO, CMTE.' 'NAZCA' 'AGUERO'
 'HUMBERTO 1?' 'THAMES' 'SANCHEZ DE LORIA' 'PICHINCHA' 'VIAMONTE'
 'PRIMERA JUNTA' 'JUNCAL' 'LACROZE, FEDERICO AV.'
 'FINOCHIETTO ENRIQUE DR.' 'URQUIZA, GRAL.' 'HUERGO, ING. AV.'
 'ORTIZ DE OCAMPO' 'GARZON, EUGENIO, GRAL. AV.' 'COCHABAMBA'
 'GARAY, JUAN DE AV.' 'COLOMBRES' 'PERGAMINO' 'GASCON' 'BERUTI'
 'DELLEPIANE, LUIS, TTE. GRAL.' 'BERON DE ASTRADA' 'ZAPIOLA' 'SUAREZ AV.'
 'ECHEVERRIA' 'GUEMES, MACACHA' 'GALLARDO, ANGEL AV.' 'SERRANO'
 'TRES ARROYOS' 'SAN PEDRITO' 'MANZONI' 'LARRAZABAL' 'VENTANA'
 'DE LOS CONSTITUYENTES AV.' 'GUEVARA' 'SEGUROLA AV.'
 'CASTILLO, RAMON S., PRES. AV.' 'PERU' 'SANTIAGO DEL ESTERO'
 'MORENO, PERITO AV.' 'TERRADA' 'MEDINA' 'YATAY' 'SAN JUAN AV.'
 'GORDILLO, TIMOTEO' 'MOM' 'YERBAL' 'JACQUES, AMADEO' 'AZCUENAGA'
 'ORO?O, NICASIO' 'MADERO, EDUARDO AV.' 'ALVAREZ, DONATO, TTE. GRAL. AV.'
 'FORMOSA' 'DIRECTORIO AV.' 'SANTANDER' 'ANDALGALA' 'CONSTITUCION'
 'REPUBLICA DE LA INDIA' 'CABILDO AV.' 'MENDOZA' 'HONDURAS AV.'
 'CASTA?ARES AV.' 'CAMPOS, LUIS M. AV.' 'MAURE' 'AVELLANEDA AV.' 'TILCARA'
 'BOLIVAR (NO OFICIAL)' 'GORRITI' 'OLIVERA AV.' 'ALCORTA, AMANCIO AV.'
 'LAFUENTE' 'BACACAY' 'BLANES, JUAN MANUEL' 'CAMARGO' 'SUAREZ'
 'JUSTO, JUAN B. AV.' 'PIEDRAS' 'TILCARA AV.' 'LOYOLA'
 'COMBATE DE LOS POZOS' 'JAURES, JEAN' 'NOGOYA' 'GOMEZ, VALENTIN'
 'MONTIEL' 'WARNES AV.' 'ROFFO, ANGEL H., DR.'
 'ANCHORENA, TOMAS MANUEL DE, DR.' 'DIAZ, CNEL. AV.'
 'SOLDADO DE LA FRONTERA AV.' 'CARRANZA, ADOLFO P.' 'LACARRA AV.'
 'MERCEDES' 'EINSTEIN, ALBERTO' 'VIALE, LUIS' 'ALTA GRACIA'
 'GOYENECHE, ROBERTO PARQUE AV.' 'BEAZLEY' 'AUSTRIA' 'LAS HERAS, GENERAL'
 'CALVO, CARLOS' 'NAZCA AV.' 'CHIVILCOY' 'GUARANI' 'SARMIENTO AV.'
 'GIRIBONE' 'GUAMINI' 'DE LA TORRE, LISANDRO' 'LARRALDE, CRISOLOGO AV.'
 'ROOSEVELT FRANKLIN D.' 'PIEDRA BUENA AV.' 'TORRES Y TENORIO, PRES.'
 'GUIRALDES, INT.' 'LAFUENTE AV.' 'SANTA FE AV.' 'CASARES AV.' 'PILAR'
 'ACOSTA, MARIANO' 'GUZMAN AV.' 'CONGRESO AV.' 'EREZCANO AV.' 'TONELERO'
 'AGOTE, LUIS DR.' 'OLAZABAL' 'BRUIX AV.' 'EZEIZA' '3 DE FEBRERO'
 'LAVALLE' 'HUGO, VICTOR']
168

In [154]:
print(hechos[['Altura', 'Dirección Normalizada']][hechos['Altura'].isnull()])
print(hechos[['Cruce', 'Dirección Normalizada']][hechos['Cruce'].isnull()])
# Mostrar registro con altura nula
print(hechos['Dirección Normalizada'][0], hechos['Altura'][1])

# Mostrar registro con altura

print(hechos['Dirección Normalizada'][2], hechos['Altura'][2])

# Mostrar registro con Cruce nulo
print(hechos['Dirección Normalizada'][2], hechos['Cruce'][2])

# Mostrar registro con Cruce

print(hechos['Dirección Normalizada'][0], hechos['Cruce'][0])

     Altura                              Dirección Normalizada
0       NaN  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...
1       NaN               PAZ, GRAL. AV. y DE LOS CORRALES AV.
3       NaN          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.
4       NaN            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.
5       NaN                   27 DE FEBRERO AV. y ESCALADA AV.
..      ...                                                ...
689     NaN                           BAIGORRIA y HUGO, VICTOR
690     NaN                     RIVADAVIA AV. y PUEYRREDON AV.
691     NaN                                  RIESTRA AV. y MOM
692     NaN         DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.
693     NaN                                GAONA AV. y TERRADA

[564 rows x 2 columns]
    Cruce                       Dirección Normalizada
2     NaN                         ENTRE RIOS AV. 2034
9     NaN                         ENTRE RIOS AV. 1366
14    NaN                                SUIPACHA 156
33    NaN                                   LIMA 1483
35    NaN  AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI
..    ...                                         ...
680   NaN                AUTOPISTA 25 DE MAYO y PASCO
685   NaN                              ESMERALDA 1359
687   NaN                              GAONA AV. 3655
694   NaN                         PERON, EVA AV. 4071
695   NaN                     PADRE CARLOS MUGICA 709

[168 rows x 2 columns]
PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., GRAL. AV. nan
ENTRE RIOS AV. 2034 2034.0
ENTRE RIOS AV. 2034 nan
PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., GRAL. AV. FERNANDEZ DE LA CRUZ, F., GRAL. AV.

Contiene 564 valores nulos, debido a que estas variables estan condicionada con la variable `Dirección Normalizada`, algunas direcciones no contienen altura he aqui el motivo de los valores nulos, por lo que no se realizaran transformaciones.

# Dirección Normalizada

In [155]:
hechos['Dirección Normalizada']

0      PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...
1                   PAZ, GRAL. AV. y DE LOS CORRALES AV.
2                                    ENTRE RIOS AV. 2034
3              LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.
4                SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.
                             ...
691                                    RIESTRA AV. y MOM
692           DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.
693                                  GAONA AV. y TERRADA
694                                  PERON, EVA AV. 4071
695                              PADRE CARLOS MUGICA 709
Name: Dirección Normalizada, Length: 691, dtype: object

In [156]:
hechos['Dirección Normalizada'].isnull().sum()

7

In [157]:
hechos[hechos['Dirección Normalizada'].isnull()]

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
38,2016-0052,1,2016-04-20,2016,4,20,20:00:00,20,AUTOPISTA LUGONES PK 10000,AUTOPISTA,...,NaN,NaN,NaN,13,Point (. .),.,.,MOTO-SD,MOTO,SD
106,2016-0136,1,2016-10-25,2016,10,25,00:00:00,0,AU BUENOS AIRES - LA PLATA KM. 4,AUTOPISTA,...,NaN,NaN,NaN,4,Point (. .),.,.,MOTO-CARGAS,MOTO,CARGAS
180,2017-0050,2,2017-04-28,2017,4,28,11:08:00,11,AU PERITO MORENO Y RAMAL ENLACE AU1/AU6,AUTOPISTA,...,NaN,NaN,NaN,9,Point (. .),.,.,MOTO-CARGAS,MOTO,CARGAS
181,2017-0051,1,2017-05-01,2017,5,1,03:47:00,3,AU DELLEPIANE 2400,AUTOPISTA,...,NaN,NaN,NaN,7,Point (. .),.,.,AUTO-AUTO,AUTO,AUTO
313,2018-0039,1,2018-04-21,2018,4,21,22:15:00,22,AUTOPISTA LUGONES KM 4.7,AUTOPISTA,...,NaN,NaN,NaN,14,Point (. .),.,.,PEATON-AUTO,PEATON,AUTO
546,2020-0026,1,2020-05-17,2020,5,17,06:40:00,6,"LUGONES, LEOPOLDO AV. KM 6,1",AUTOPISTA,...,NaN,NaN,NaN,14,Point (. .),.,.,MOTO-OBJETO FIJO,MOTO,OBJETO FIJO
621,2021-0023,1,2021-03-01,2021,3,1,09:20:00,9,"AU BUENOS AIRES LA PLATA KM 4,5",AUTOPISTA,...,NaN,NaN,NaN,4,Point (. .),.,.,MOTO-CARGAS,MOTO,CARGAS

In [158]:
hechos[hechos['Dirección Normalizada'] == 'SD']

Empty DataFrame
Columns: [ID, N_VICTIMAS, FECHA, AAAA, MM, DD, HORA, HH, LUGAR_DEL_HECHO, TIPO_DE_CALLE, Calle, Altura, Cruce, Dirección Normalizada, COMUNA, XY (CABA), pos x, pos y, PARTICIPANTES, VICTIMA, ACUSADO]
Index: []

[0 rows x 21 columns]

In [159]:
# Eliminar registros con Dirección Normalizada nula

hechos.dropna(subset=['Dirección Normalizada'], inplace=True)

# COMUNA

In [160]:
print(hechos['COMUNA'].unique())

[ 8  9  1 11 15  4  7 12  3 13 14 10  6  2  5  0]

Hay registros que no estan en el rango de 1-15 (0)

In [161]:
hechos[hechos['COMUNA'] == 0]

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
139,2016-0174,1,2016-12-27,2016,12,27,00:00:00,0,AUTOPISTA 25 DE MAYO,AUTOPISTA,...,NaN,NaN,AUTOPISTA 25 DE MAYO,0,Point (. .),.,.,SD-SD,SD,SD

Se identifico un registro con valor 0, se eliminara este registro.

In [162]:
hechos['COMUNA'].replace(0, pd.NA, inplace=True)

hechos.dropna(subset=['COMUNA'], inplace=True)

# XY (CABA), pos x, pos y

In [163]:
print(hechos['XY (CABA)'].unique())
print(hechos['pos x'].unique())
print(hechos['pos y'].unique())
print(hechos['XY (CABA)'].dtype)
print(hechos['pos x'].dtype)
print(hechos['pos y'].dtype)

['Point (98896.78238426 93532.43437792)'
 'Point (95832.05571093 95505.41641999)'
 'Point (106684.29090040 99706.57687843)'
 'Point (99840.65224780 94269.16534422)'
 'Point (106980.32827929 100752.16915795)'
 'Point (101721.59002217 93844.25656649)'
 'Point (96545.87592078 102330.67262199)'
 'Point (107595.35084333 101797.50052813)'
 'Point (106616.41069662 100496.44662323)'
 'Point (102357.43746828 103343.52002839)'
 'Point (108661.59115206 98481.75445555)'
 'Point (101228.61094416 96623.72136186)'
 'Point (95727.37083199 97179.35560349)'
 'Point (107684.31807562 102519.17333314)'
 'Point (101074.94198885 99848.19369046)'
 'Point (107507.39502374 102046.08333077)'
 'Point (100077.95205948 91571.23307293)'
 'Point (97350.75566590 109083.19420265)'
 'Point (101679.82794245 98973.02976850)'
 'Point (107457.87314266 103212.28518029)'
 'Point (99037.31284333 109733.12041651)'
 'Point (99327.01838497 92326.91130631)'
 'Point (105230.98315750 97613.97258373)'
 'Point (106513.41423248 102752.75354401)'
 'Point (107808.84957181 99174.17105826)'
 'Point (100049.60313526 98412.21255444)'
 'Point (96926.79887463 94490.76318635)'
 'Point (105252.60308563 102264.96028996)'
 'Point (100232.38564985 99530.25843190)'
 'Point (98623.04338909 94933.06478837)'
 'Point (102857.73817324 99148.76714504)'
 'Point (99620.34936816 110483.29286598)'
 'Point (107412.19098904 100391.02557777)'
 'Point (101440.29935254 104167.40204334)' 'Point (. .)'
 'Point (99106.14718950 93761.32882893)'
 'Point (98073.80557770 105955.73972818)'
 'Point (97832.57143731 93489.83736533)'
 'Point (105787.74102401 105502.98340149)'
 'Point (103094.06446966 105842.29634122)'
 'Point (107411.76356149 100408.31441284)'
 'Point (107434.83290791 100217.70308007)'
 'Point (97106.70264812 99970.19547024)'
 'Point (101010.75965434 102062.18185970)'
 'Point (98052.13008621 94912.60873025)'
 'Point (106673.12856878 104998.99234220)'
 'Point (106612.54991859 100244.75667446)'
 'Point (97531.24792840 101000.15957301)'
 'Point (96731.44252651 94668.88351657)'
 'Point (98963.32962830 95620.61360192)'
 'Point (100109.22264405 102851.86942760)'
 'Point (108532.37320501 102648.40418720)'
 'Point (105354.74322032 101621.63182427)'
 'Point (100757.94817512 108943.96108781)'
 'Point (93950.50587297 98883.37644525)'
 'Point (97805.54034401 107789.89169078)'
 'Point (103719.51591058 98555.13443768)'
 'Point (101413.41644585 100430.31523295)'
 'Point (107539.54864414 103093.65031518)'
 'Point (103621.92252760 96885.28433165)'
 'Point (97801.31825511 99194.93911759)'
 'Point (107762.62066736 100018.90176187)'
 'Point (96492.89040317 106832.19475660)'
 'Point (102842.06561704 108587.10659007)'
 'Point (103997.04813615 102012.34139150)'
 'Point (101804.61714036 100693.45218194)'
 'Point (95061.77375682 103748.74085597)'
 'Point (106687.13301820 101510.97040757)'
 'Point (105765.97394356 100631.47718024)'
 'Point (94486.28631712 103468.59928582)'
 'Point (97098.48468623 109019.96106626)'
 'Point (93946.81673714 97681.68907836)'
 'Point (96625.80612216 95129.90776954)'
 'Point (99720.41444035 97007.69579491)'
 'Point (100905.28580812 104982.19279501)'
 'Point (107558.64146875 104433.48706482)'
 'Point (108408.31858686 97219.56218484)'
 'Point (94544.31344300 99185.28796442)'
 'Point (95506.35959227 96696.89655626)'
 'Point (98961.36262767 105838.76329094)'
 'Point (107392.50226602 100712.59265582)'
 'Point (96998.81124177 98183.20743664)'
 'Point (104111.05146856 103917.57944765)'
 'Point (97608.87024259 108884.67029908)'
 'Point (105865.95849347 105162.71037105)'
 'Point (107696.68171812 100254.76268710)'
 'Point (96944.69676081 107291.52292157)'
 'Point (99150.75069529 97484.46650280)'
 'Point (101099.34592952 98750.07827754)'
 'Point (100053.89791316 100046.73776995)'
 'Point (97532.91184699 98538.89061454)'
 'Point (94275.54271123 100886.87954649)'
 'Point (102048.72946345 95839.63478990)'
 'Point (104049.28528337 99858.37522846)'
 'Point (107720.24059557 100176.85101454)'
 'Point (105921.45515383 98209.53178328)'
 'Point (104853.84131654 100497.93573387)'
 'Point (105619.82089682 105083.85914124)'
 'Point (97612.37609226 94761.81268260)'
 'Point (103734.76257993 107235.78328415)'
 'Point (95222.93546397 104315.24453153)'
 'Point (100385.69739031 107770.04028070)'
 'Point (103965.45958231 107084.94812768)'
 'Point (100700.71684791 107520.92282315)'
 'Point (108069.68986814 104046.20018024)'
 'Point (109494.82838112 99532.69117874)'
 'Point (101657.76119068 107735.39237736)'
 'Point (106147.25140863 99876.44981079)'
 'Point (106817.01972475 101248.18030272)'
 'Point (99810.88349598 103818.87868694)'
 'Point (104996.91619776 97395.92929535)'
 'Point (99888.30162107 97709.27452060)'
 'Point (103130.82393478 103817.27945358)'
 'Point (97546.12845734 94093.36420523)'
 'Point (94107.02905618 100169.73297345)'
 'Point (105219.14271583 101089.92439911)'
 'Point (98856.51878317 101315.60184716)'
 'Point (94867.91408532 99212.26216105)'
 'Point (103490.75904616 105613.31878847)'
 'Point (100856.34310085 104890.83521057)'
 'Point (103673.23003122 98676.84527702)'
 'Point (108623.21898604 100090.41541188)'
 'Point (98526.50846677 108043.08552265)'
 'Point (96082.96647324 107261.96873833)'
 'Point (108916.48040002 100856.88142642)'
 'Point (104044.75501725 99724.84699960)'
 'Point (99615.63172945 99306.93173343)'
 'Point (100243.74197213 99962.81893983)'
 'Point (108597.31948169 101875.41306445)'
 'Point (104920.46334566 104589.99681258)'
 'Point (105541.07964363 101532.48653010)'
 'Point (99757.62471161 102105.99371863)'
 'Point (106759.07058844 98352.11326541)'
 'Point (107491.43483173 101547.26343171)'
 'Point (102213.80136590 104917.03799721)'
 'Point (104341.1368196 100202.74363294)'
 'Point (102535.57417570 100108.76675064)'
 'Point (96563.66494817 108815.73881056)'
 'Point (104914.66823035 97637.72796868)'
 'Point (106744.80812193 97588.11558612)'
 'Point (97378.59173196 108741.41437861)'
 'Point (106454.66355436 103285.14730222)'
 'Point (107547.76713701 100705.57738660)'
 'Point (103145.91571023 105359.30690018)'
 'Point (107308.24054153 102678.45528316)'
 'Point (99762.20699423 99968.05446003)'
 'Point (102489.38230491 97228.94942016)'
 'Point (104113.67806500 97722.68219304)'
 'Point (107333.53318866 99701.77552382)'
 'Point (100783.70757056 101919.87125456)'
 'Point (98009.35575364 97985.81952007)'
 'Point (99375.77435905 96732.87189547)'
 'Point (104889.75647602 100057.93817815)'
 'Point (97652.09135282 93973.55833508)'
 'Point (94371.21426086 102884.21739121)'
 'Point (103464.34360929 105543.78205193)'
 'Point (109583.11620052 102006.72069921)'
 'Point (95300.18060161 105287.23850698)'
 'Point (101662.32423755 98406.44885071)'
 'Point (102290.82648731 109281.08885461)'
 'Point (100774.70463767 99328.98632835)'
 'Point (94388.40460408 100522.78812728)'
 'Point (99648.31069819 95261.11808541)'
 'Point (102273.01728657 97084.66236498)'
 'Point (97173.99360188 94265.65054023)'
 'Point (108050.74089604 97335.15201103)'
 'Point (97843.76024114 104700.29820723)'
 'Point (97032.68537217 105507.05805581)'
 'Point (107271.27725903 103337.46347012)'
 'Point (107433.79647713 100255.68319210)'
 'Point (100333.14201607 95123.00813458)'
 'Point (106445.10866138 103387.80115442)'
 'Point (95477.60201436 99478.59069542)'
 'Point (107531.03549571 101417.11038758)'
 'Point (107958.58079244 102597.49225224)'
 'Point (107903.91828587 98767.43091425)'
 'Point (100300.69930045 102792.78597597)'
 'Point (102703.30911569 100138.40769771)'
 'Point (102520.03961549 96105.29592085)'
 'Point (94644.00300729 96592.22735507)'
 'Point (95907.08722675 103463.22327776)'
 'Point (97389.59663507 105213.53381695)'
 'Point (105089.38820014 102773.44772064)'
 'Point (94281.31244858 99043.29027489)'
 'Point (107498.83241886 102238.54924157)'
 'Point (107160.34141948 105678.38284277)'
 'Point (103115.59520137 104964.08461543)'
 'Point (105202.26736061 101269.73269565)'
 'Point (97070.50716478 98268.08001276)'
 'Point (106636.30041967 99991.34072603)'
 'Point (107180.90591568 104682.54945160)'
 'Point (108315.72323297 99748.45783960)'
 'Point (94914.28538682 98912.56901137)'
 'Point (104800.65774098 101563.94663965)'
 'Point (108741.48238670 100448.08502809)'
 'Point (95246.78684010 97935.32361317)'
 'Point (94866.55993974 104164.40879727)'
 'Point (97850.57417090 109546.39428377)'
 'Point (102474.90818824 108830.74789029)'
 'Point (94212.26181299 101286.25735606)'
 'Point (104068.94257873 103491.45652529)'
 'Point (99608.90354249 108823.89449537)'
 'Point (100563.22594607 99771.56223988)'
 'Point (103600.34605991 107446.36084135)'
 'Point (106103.99852157 101567.67895783)'
 'Point (101644.77699748 106480.78805418)'
 'Point (105750.92237188 97579.79677541)'
 'Point (107538.91933237 101188.13128502)'
 'Point (103483.20578848 105425.94020024)'
 'Point (100245.64635241 109464.60244956)'
 'Point (99266.22533505 99180.83096967)'
 'Point (108513.43549456 103032.95078343)'
 'Point (103948.02389064 98549.15451723)'
 'Point (100479.14412395 98812.52258620)'
 'Point (107918.77617420 103716.42961253)'
 'Point (106632.70892338 104910.17381357)'
 'Point (103803.42869640 99818.79654291)'
 'Point (95357.86744200 105380.41895972)'
 'Point (108016.39016447 97439.36817481)'
 'Point (99113.17852207 96319.06728520)'
 'Point (99518.38660571 95241.63338177)'
 'Point (101904.43474476 104150.89892205)'
 'Point (99732.19478660 94453.36361177)'
 'Point (98466.20276785 94207.42419155)'
 'Point (104713.04838502 103467.44528033)'
 'Point (102105.12699179 101749.49668435)'
 'Point (99243.41866587 97782.67879316)'
 'Point (98575.30034704 103283.44421792)'
 'Point (99796.45945783 92847.91633262)'
 'Point (101915.86954232 95727.75538814)'
 'Point (99355.48397222 103660.98712619)'
 'Point (104127.10295709 97119.53980201)'
 'Point (95458.27090734 104045.28333021)'
 'Point (100065.47249269 98381.80497378)'
 'Point (101160.07257435 94368.23344193)'
 'Point (103312.47684665 100458.27902411)'
 'Point (99897.24182072 102443.29154512)'
 'Point (104266.88124229 101889.22080612)'
 'Point (96405.76679348 94981.38013791)'
 'Point (105155.42991407 100540.06938064)'
 'Point (108605.31247489 101604.53195530)'
 'Point (95589.03838155 98881.22999034)'
 'Point (108130.20782757 97076.54120716)'
 'Point (104752.14395609 97617.14934540)'
 'Point (103186.65733155 101217.09689755)'
 'Point (106688.43418876 99459.27505947)'
 'Point (100674.98109200 100299.64949548)'
 'Point (94007.62506099 98145.35456663)'
 'Point (94764.11350214 103903.32150283)'
 'Point (99317.63492514 100172.19114010)'
 'Point (98285.13000363 96624.14779705)'
 'Point (106229.70400707 100696.43939679)'
 'Point (108138.18410245 101140.78821350)'
 'Point (101348.13972450 102808.02053976)'
 'Point (100183.96103971 109533.84269558)'
 'Point (108641.50518777 101075.93727953)'
 'Point (102079.59903748 100474.45881577)'
 'Point (94340.14761734 99250.24722124)'
 'Point (108868.80749430 101370.51785663)'
 'Point (108796.38792642 100177.06810505)'
 'Point (96810.81688812 99875.56613013)'
 'Point (106639.47032605 104255.89970551)'
 'Point (99466.65991849 94317.70888094)'
 'Point (97860.62977748 106812.00802724)'
 'Point (102067.32140821 97610.71255013)'
 'Point (107053.47849253 98047.93724144)'
 'Point (99418.67591727 99840.67619219)'
 'Point (108363.47256437 98202.84498754)'
 'Point (106550.65433457 104158.41702434)'
 'Point (101207.19032483 96015.90575056)'
 'Point (105634.57202683 98201.36000813)'
 'Point (108149.86840397 98842.98534187)'
 'Point (102035.73876399 100936.73706899)'
 'Point (99305.05235104 105657.19134383)'
 'Point (100337.26455822 100756.41076314)'
 'Point (104283.01090451 97171.08656182)'
 'Point (104051.46146857 99117.09528964)'
 'Point (99275.15851476 98531.15835355)'
 'Point (99001.33520474 100973.19474422)'
 'Point (99641.71055660 105570.42188351)'
 'Point (99468.64184992 101272.71412938)'
 'Point (101491.71965442 106698.43843791)'
 'Point (96143.57848535 100026.85558450)'
 'Point (105786.93203839 103775.29320399)'
 'Point (100003.66169818 100008.18099088)'
 'Point (97118.17245497 103585.17867883)'
 'Point (105923.35790409 103271.83194351)'
 'Point (106840.31999667 102262.72809661)'
 'Point (100590.76036525 106235.55299971)'
 'Point (103711.66698694 98495.65433114)'
 'Point (107026.83754260 98858.75172681)'
 'Point (97438.46582767 101907.03915052)'
 'Point (105715.04318224 101174.58167004)'
 'Point (100808.33159423 105557.81994917)'
 'Point (99925.51296558 100002.14427355)'
 'Point (100107.11808300 108354.57023193)'
 'Point (100606.16651489 107458.45493347)'
 'Point (109491.72835084 98425.60443682)'
 'Point (96798.08806617 104278.02817622)'
 'Point (104834.84104085 103313.26202067)'
 'Point (98495.84519532 106440.03052817)'
 'Point (105482.77183741 101155.54165898)'
 'Point (94825.31796080 98898.07278223)'
 'Point (106436.50690531 100845.32785530)'
 'Point (102567.54814228 104264.87527568)'
 'Point (104724.05358972 99878.51159963)'
 'Point (105911.62147898 101065.51501699)'
 'Point (108473.00357935 103295.64162815)'
 'Point (100435.26388900 98861.53271694)'
 'Point (107493.20906271 104038.93317074)'
 'Point (100750.52062158 104691.17506829)'
 'Point (107891.26340037 99945.61487141)'
 'Point (100718.69831349 99996.27412808)'
 'Point (105900.94104333 103295.18325601)'
 'Point (104963.31095539 100886.97438212)'
 'Point (108808.25931028 102022.90885862)'
 'Point (98224.62123059 93867.97738800)'
 'Point (106218.96559101 97510.98250186)'
 'Point (99438.84176266 99501.28380301)'
 'Point (105470.75546311 105320.72785650)'
 'Point (104647.18963470 103830.17880585)'
 'Point (101453.89687005 98180.39027169)'
 'Point (97148.03881747 96734.79106149)'
 'Point (98491.08733048 93092.87943671)'
 'Point (108993.20201253 100735.24332429)'
 'Point (97534.35415051 97682.40955825)'
 'Point (104296.57153484 99891.67281595)'
 'Point (102791.00899168 95424.06973029)'
 'Point (103662.91363929 103496.49206019)'
 'Point (107004.02001368 99798.84856249)'
 'Point (104734.93787233 104821.22705013)'
 'Point (99624.29795829 97569.69801131)'
 'Point (101692.57924565 95312.63822646)'
 'Point (102819.52927414 96448.46140692)'
 'Point (99203.46279192 92552.75548716)'
 'Point (109273.33013929 100616.46322293)'
 'Point (98376.44189669 109821.71138325)'
 'Point (104810.02928662 98097.69340075)'
 'Point (101577.07056955 98313.98170453)'
 'Point (102437.44187502 108614.72855724)'
 'Point (105258.35368554 102122.93231400)'
 'Point (109333.85016626 102728.06777580)'
 'Point (108501.28725227 103169.39367565)'
 'Point (102852.69197214 103016.76479974)'
 'Point (99423.87045126 97756.09331484)'
 'Point (101521.41058610 103279.18839709)'
 'Point (99245.93828707 101610.8222803)'
 'Point (106692.15004353 101239.02351805)'
 'Point (93987.63954589 98477.26093452)'
 'Point (97213.03214767 94392.58930391)'
 'Point (98224.84159668 96577.14272605)'
 'Point (105244.38396064 102386.61371612)'
 'Point (102489.86457298 96266.15892101)'
 'Point (98237.46824855 106343.83342545)'
 'Point (96684.78779898 99093.85665638)'
 'Point (98704.10681045 95222.62689520)'
 'Point (94668.77734942 99160.32825286)'
 'Point (104289.92773867 97606.13539657)'
 'Point (93889.86789861 98745.59348173)'
 'Point (95720.94836751 106663.03756022)'
 'Point (94027.41355272 98150.01779732)'
 'Point (101200.55632600 104694.24798650)'
 'Point (97531.36286491 100173.61049110)'
 'Point (108685.90894590 103124.78289557)'
 'Point (106275.90279188 106304.98623165)'
 'Point (103649.67568294 98786.92074818)'
 'Point (108124.38297421 101840.19801704)'
 'Point (99900.22869225 100014.51595495)'
 'Point (107198.03031731 102023.53206745)'
 'Point (95944.83421152 100945.68379559)'
 'Point (101510.09611838 98933.71958961)'
 'Point (109469.86887005 101709.86665960)'
 'Point (104420.68512694 100931.98574919)'
 'Point (95716.93710226 106295.47905158)'
 'Point (97912.79273192 98756.38729095)'
 'Point (100794.20933352 97609.18063839)'
 'Point (97439.07314838 103559.40773606)'
 'Point (99087.21233087 97384.56622913)'
 'Point (94701.87719386 99493.36109269)'
 'Point (104292.73762877 108227.37900690)'
 'Point (103153.61467028 102057.67908768)'
 'Point (98650.97430792 93088.91481914)'
 'Point (108038.17400278 100802.81492813)'
 'Point (103359.87920798 106617.17056502)'
 'Point (94949.53051500 96309.49139706)'
 'Point (98072.98959434 94742.80804806)'
 'Point (102701.07793891 98301.55899449)'
 'Point (95105.42229190 104734.49416290)'
 'Point (96988.34526261 103575.43345979)'
 'Point (107350.48403234 99520.90259673)'
 'Point (105883.57359899 101434.40486977)'
 'Point (101287.58627255 109848.96522762)'
 'Point (101175.50098927 108378.70762331)'
 'Point (104622.17042668 99282.25347815)'
 'Point (100537.72694403 100405.74808196)'
 'Point (93955.07404645 99209.29091025)'
 'Point (104468.07400702 102205.91009215)'
 'Point (105815.73438780 103786.90549585)'
 'Point (100255.56175905 102594.14179920)'
 'Point (100800.05107565 100531.46552448)'
 'Point (108602.89777103 103429.39485413)'
 'Point (99921.70768730 102754.71427746)'
 'Point (100726.63402530 97597.06610219)'
 'Point (107693.66022765 103185.01912141)'
 'Point (102429.80070706 100864.42075191)'
 'Point (105091.36704114 101058.15092586)'
 'Point (101025.65409402 109205.71453455)'
 'Point (101894.68493124 99164.78448252)'
 'Point (95590.61347415 96760.29404728)'
 'Point (107444.95821447 100509.15466740)'
 'Point (104305.46011381 100986.83752228)'
 'Point (104600.49945984 105930.85721602)'
 'Point (98817.74986778 110096.31367495)'
 'Point (107049.58656184 99550.26208324)'
 'Point (100924.23883176 100986.01051740)'
 'Point (100441.31384072 107499.63270409)'
 'Point (104128.51577643 103898.77571857)'
 'Point (109126.17010339 98991.49558123)'
 'Point (99896.72991309 96585.69018400)'
 'Point (98264.06251394 104989.86881414)'
 'Point (108724.12468316 102928.79394095)'
 'Point (100414.85185956 100661.22751226)'
 'Point (101957.99726887 107949.81115534)'
 'Point (96064.06591151 99221.69236283)'
 'Point (107261.50953067 99806.16899068)'
 'Point (98376.49615363 99359.41534876)'
 'Point (101036.85652575 107926.87651681)'
 'Point (101714.11981913 107461.10208167)'
 'Point (101017.68913992 104676.11449993)'
 'Point (103996.06089673 97239.27066069)'
 'Point (101964.06573044 97768.88820027)'
 'Point (97458.87181153 98502.45008355)'
 'Point (103516.29283702 96305.80102228)'
 'Point (105355.77079994 99994.97457130)'
 'Point (103342.29763549 104114.07863350)'
 'Point (98504.80160700 97011.97752137)'
 'Point (98982.27543524 99337.43508034)'
 'Point (99649.53744486 105547.74929043)'
 'Point (99830.29053639 110496.05308488)'
 'Point (108029.19662631 97048.95529785)'
 'Point (108408.31866027 97219.56223456)'
 'Point (105980.99138544 105385.93253091)'
 'Point (104770.59856807 97235.72066953)'
 'Point (104133.42235616 101175.18161468)'
 'Point (100173.09831701 104773.73030321)'
 'Point (103065.99442998 96457.67469916)'
 'Point (98049.89254647 96769.28504384)'
 'Point (99777.28948169 99222.14556838)'
 'Point (97311.79828581 99453.65686299)'
 'Point (100960.33601283 104532.07598431)'
 'Point (98491.73236150 106110.45743791)'
 'Point (109247.85081573 99794.76658137)'
 'Point (96669.91669285 97846.12432372)'
 'Point (101631.52816900 103735.20218464)'
 'Point (109831.09861352 99447.57530396)'
 'Point (99859.01807773 102240.12407554)'
 'Point (101799.19412891 103552.67600212)'
 'Point (107762.62066755 100018.90176184)'
 'Point (108041.76772318 100219.10582069)'
 'Point (98724.36593359 97905.39654686)'
 'Point (101097.15913487 104373.72916577)'
 'Point (97512.85370485 105056.21473822)'
 'Point (103875.40694167 97709.33732832)'
 'Point (94600.31582329 98648.40911008)'
 'Point (98963.45381519 99690.23941640)'
 'Point (96164.17004077 101559.58637156)'
 'Point (102219.66522967 104119.42339682)'
 'Point (101201.50959665 98092.52358781)'
 'Point (106413.35913221 102215.84332055)'
 'Point (106672.04348602 102224.86809233)'
 'Point (101287.27262066 97242.60480808)'
 'Point (107495.74012081 101415.07897373)'
 'Point (105198.52795163 103462.44828321)'
 'Point (103984.76403716 102579.64869142)'

Hay registros sin coordenadas asignada, se eliminaran estos registros.

In [164]:
con1 = (hechos['XY (CABA)'] == 'Point (. .)')
con2 = (hechos['pos x'] == '.') | (hechos['pos y'] == '.')
hechos[con1 | con2]

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
35,2016-0049,1,2016-04-17,2016,4,17,00:00:00,0,AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI KM....,AUTOPISTA,...,NaN,NaN,AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI,4,Point (. .),-58.37714647568196,-34.63657525428238,SD-SD,SD,SD
71,2016-0096,1,2016-07-25,2016,7,25,07:00:00,7,"AUTOPISTA DELLEPIANE LUIS TTE. GRAL. KM. 2,3",AUTOPISTA,...,NaN,NaN,AUTOPISTA DELLEPIANE LUIS TTE. GRAL.,8,Point (. .),-58.47433193007387,-34.66684950051973,MOTO-CARGAS,MOTO,CARGAS
176,2017-0042,1,2017-04-10,2017,4,10,09:00:00,9,AV. LEOPOLDO LUGONES PKM 6900,GRAL PAZ,...,NaN,NaN,"LUGONES, LEOPOLDO AV.",14,Point (. .),.,.,MOTO-CARGAS,MOTO,CARGAS
256,2017-0140,1,2017-11-19,2017,11,19,23:22:00,23,AU ARTURO FRONDIZI PKM 3100,AUTOPISTA,...,NaN,NaN,AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI,4,Point (. .),.,.,MOTO-PASAJEROS,MOTO,PASAJEROS
559,2020-0039,1,2020-09-01,2020,9,1,19:17:00,19,MURGUIONDO 2700,CALLE,...,NaN,NaN,MURGUIONDO,9,Point (. .),.,.,PEATON-CARGAS,PEATON,CARGAS

`XY (CABA)` contiene coordenadas planas en el sistema de referencia de la Ciudad de Buenos Aires, `pos x` y `pos y` contienen coordenadas geograficas en el sistema de referencia WGS84 pero el tipo de dato es Object, debe ser transformado a float luego de realizar la limpieza.

Existen registros de `XY (CABA)` que estan sin especificar, pero en las variables `pos x` y `pos y` si estan registrados, por lo que se procedera a eliminaran solo los registros que no esten registrados en ninguna de las variables.

In [165]:
hechos = hechos[~(con2)]

In [166]:
# convertir a float las columnas pos x y pos y
hechos['pos x'] = hechos['pos x'].astype(float)

hechos['pos y'] = hechos['pos y'].astype(float)

In [167]:
# verificar tipo de datos

print(hechos['pos x'].dtype)
print(hechos['pos y'].dtype)

float64
float64

# PARTICIPANTES, VICTIMA, ACUSADO

In [168]:
print(hechos['PARTICIPANTES'].unique())
print(hechos['VICTIMA'].unique())
print(hechos['ACUSADO'].unique())

['MOTO-AUTO' 'AUTO-PASAJEROS' 'MOTO-SD' 'MOTO-PASAJEROS'
 'MOTO-OBJETO FIJO' 'MOTO-CARGAS' 'PEATON-AUTO' 'PEATON-MOTO'
 'PEATON-PASAJEROS' 'AUTO-AUTO' 'AUTO-OBJETO FIJO' 'PEATON-CARGAS'
 'MOTO-MOTO' 'MULTIPLE' 'SD-SD' 'AUTO-CARGAS' 'AUTO-SD' 'MOTO-MOVIL'
 'CARGAS-CARGAS' 'PEATON-SD' 'BICICLETA-CARGAS' 'SD-CARGAS'
 'BICICLETA-PASAJEROS' 'PASAJEROS-PASAJEROS' 'MOVIL-PASAJEROS'
 'CARGAS-OBJETO FIJO' 'PEATON-BICICLETA' 'SD-AUTO' 'CARGAS-AUTO'
 'BICICLETA-AUTO' 'MOTO-BICICLETA' 'SD-MOTO' 'MOVIL-CARGAS'
 'PASAJEROS-AUTO' 'AUTO-MOVIL' 'CARGAS-PASAJEROS' 'BICICLETA-TREN'
 'BICICLETA-OTRO' 'MOTO-OTRO' 'PEATON_MOTO-MOTO' 'PASAJEROS-SD']
['MOTO' 'AUTO' 'PEATON' 'SD' 'CARGAS' 'BICICLETA' 'PASAJEROS' 'MOVIL'
 'OBJETO FIJO' 'PEATON_MOTO']
['AUTO' 'PASAJEROS' 'SD' 'OBJETO FIJO' 'CARGAS' 'MOTO' 'MULTIPLE' 'OTRO'
 'BICICLETA' 'TREN']



Se realizara una imputación del valor mas frecuente para las variables `VICTIMA` y `ACUSADO` que contienen valores 'SD', luego con esos datos se creara la columna `PARTICIPANTES` que es la concatenación de `VICTIMA` y `ACUSADO` excepto cuando `ACUSADO` contiene "MULTIPLE".
Se verificara que todos los valores de `PARTICIPANTES` correspondan a los valores de `VICTIMA` y `ACUSADO`.
Se detecto una inconsistencia en la variable `VICTIMA` , contienen registros con el valor 'OBJETO FIJO' o 'PEATON_MOTO' que no estan en el diccionario , por lo que se deben tratar.

In [169]:

# Filtrar registros donde 'VICTIMA' o 'ACUSADO' contienen 'sd' (insensible a mayúsculas/minúsculas)
filtro_contiene_sd = hechos['VICTIMA'].str.contains(
    'sd', case=False) | hechos['ACUSADO'].str.contains('sd', case=False)

# Aplicar el filtro para obtener filas con valores potencialmente inválidos en 'VICTIMA' o 'ACUSADO'
registros_con_sd = hechos.loc[filtro_contiene_sd,
                              ['PARTICIPANTES', 'VICTIMA', 'ACUSADO']]

# Capturar los índices de las filas filtradas para futura referencia
indices_con_sd = registros_con_sd.index.tolist()
print(
    f"Número de registros con 'sd' en 'VICTIMA' o 'ACUSADO': {len(registros_con_sd)}")


# Obtener el valor más frecuente para 'VICTIMA' y 'ACUSADO' en todo el DataFrame
valor_frecuente_victima = hechos['VICTIMA'].mode().iloc[0]
valor_frecuente_acusado = hechos['ACUSADO'].mode().iloc[0]

# Iterar sobre los índices de registros inválidos para imputación
for indice in indices_con_sd:
    # Imputar 'VICTIMA' y 'ACUSADO' con su respectivo valor más frecuente
    hechos.at[indice, 'VICTIMA'] = valor_frecuente_victima
    hechos.at[indice, 'ACUSADO'] = valor_frecuente_acusado

    # Actualizar 'PARTICIPANTES' con los valores imputados de 'VICTIMA' y 'ACUSADO'
    valor_imputado_victima = hechos.at[indice, 'VICTIMA']
    valor_imputado_acusado = hechos.at[indice, 'ACUSADO']
    valor_imputado_participantes = f"{valor_imputado_victima}-{valor_imputado_acusado}"
    hechos.at[indice, 'PARTICIPANTES'] = valor_imputado_participantes

# Verificar las filas actualizadas para asegurar que la imputación fue exitosa
hechos.loc[indices_con_sd, ['PARTICIPANTES', 'VICTIMA', 'ACUSADO']]

Número de registros con 'sd' en 'VICTIMA' o 'ACUSADO': 23

    PARTICIPANTES VICTIMA ACUSADO
3       MOTO-AUTO    MOTO    AUTO
32      MOTO-AUTO    MOTO    AUTO
35      MOTO-AUTO    MOTO    AUTO
57      MOTO-AUTO    MOTO    AUTO
76      MOTO-AUTO    MOTO    AUTO
83      MOTO-AUTO    MOTO    AUTO
88      MOTO-AUTO    MOTO    AUTO
92      MOTO-AUTO    MOTO    AUTO
105     MOTO-AUTO    MOTO    AUTO
112     MOTO-AUTO    MOTO    AUTO
126     MOTO-AUTO    MOTO    AUTO
160     MOTO-AUTO    MOTO    AUTO
164     MOTO-AUTO    MOTO    AUTO
197     MOTO-AUTO    MOTO    AUTO
201     MOTO-AUTO    MOTO    AUTO
214     MOTO-AUTO    MOTO    AUTO
216     MOTO-AUTO    MOTO    AUTO
269     MOTO-AUTO    MOTO    AUTO
393     MOTO-AUTO    MOTO    AUTO
397     MOTO-AUTO    MOTO    AUTO
450     MOTO-AUTO    MOTO    AUTO
457     MOTO-AUTO    MOTO    AUTO
620     MOTO-AUTO    MOTO    AUTO

In [170]:
hechos[(hechos['VICTIMA'] == "OBJETO FIJO") |
       (hechos['VICTIMA'] == "PEATON_MOTO")]

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Altura,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO
230,2017-0108,2,2017-09-02,2017,9,2,04:53:00,4,AV. GRAL. PAZ Y MACHAIN,GRAL PAZ,...,NaN,MACHAIN,"PAZ, GRAL. AV. y MACHAIN",12,Point (97098.48468623 109019.96106626),-58.494911,-34.547956,AUTO-OBJETO FIJO,OBJETO FIJO,AUTO
583,2020-0063,2,2020-12-05,2020,12,5,07:10:00,7,NUEVA YORK Y ALTA GRACIA,CALLE,...,NaN,ALTA GRACIA,NUEVA YORK y ALTA GRACIA,11,Point (94080.62190808 102083.62453795),-58.527838,-34.610470,PEATON_MOTO-MOTO,PEATON_MOTO,MOTO

Se intercambiaran los valores de `VICTIMA` y `ACUSADO` ya que se encuentran invertidos y se borrara el registro con el valor 'PEATON_MOTO'.

In [171]:

# Intercambiar valores de 'VICTIMA' y 'ACUSADO' para registros donde 'VICTIMA' es "OBJETO FIJO"

mask = hechos['VICTIMA'] == "OBJETO FIJO"
hechos.loc[mask, ['VICTIMA', 'ACUSADO']] = hechos.loc[mask, ['ACUSADO', 'VICTIMA']].values

# Eliminar el registro donde 'VICTIMA' es "PEATON_MOTO"
hechos = hechos[hechos['VICTIMA'] != "PEATON_MOTO"]

In [172]:
hechos['PARTICIPANTES_TEORICO'] = hechos['VICTIMA'] + '-' + hechos['ACUSADO']

In [173]:
filtro = hechos['PARTICIPANTES'] != hechos['PARTICIPANTES_TEORICO']

hechos[filtro]

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,Cruce,Dirección Normalizada,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO,PARTICIPANTES_TEORICO
31,2016-0044,1,2016-03-31,2016,3,31,19:40:00,19,AV JOSE MARIA MORENO Y BALBASTRO,AVENIDA,...,BALBASTRO,"MORENO, JOSE MARIA AV. y BALBASTRO",7,Point (102857.73817324 99148.76714504),-58.432132,-34.636940,MULTIPLE,MOTO,MULTIPLE,MOTO-MULTIPLE
62,2016-0085,1,2016-06-29,2016,6,29,22:00:00,22,AVDA ITE FRANCISCO RABANAL & AVDA EREZCANO,AVENIDA,...,EREZCANO,"RABANAL, FRANCISCO, INTENDENTE AV. y EREZCANO",4,Point (103621.92252760 96885.28433165),-58.423788,-34.657341,MOTO-MOVIL,MOTO,OTRO,MOTO-OTRO
143,2016-0178,1,2016-12-30,2016,12,30,16:18:00,16,REPUBLICA BOLIVARIANA DE VENEZUELA Y SAAVEDRA,CALLE,...,SAAVEDRA,REPUBLICA BOLIVARIANA DE VENEZUELA y SAAVEDRA,3,Point (105541.07964363 101532.48653010),-58.402882,-34.615441,MULTIPLE,PEATON,MULTIPLE,PEATON-MULTIPLE
146,2017-0007,1,2017-01-11,2017,1,11,17:00:00,17,LIMA Y MEXICO,CALLE,...,MEXICO,LIMA y MEXICO,1,Point (107491.43483173 101547.26343171),-58.381617,-34.615295,MULTIPLE,PEATON,MULTIPLE,PEATON-MULTIPLE
153,2017-0014,1,2017-01-28,2017,1,28,08:27:00,8,AV. DONADO Y ARIAS,AVENIDA,...,ARIAS,DONADO y ARIAS,12,Point (97378.59173196 108741.41437861),-58.491860,-34.550468,MULTIPLE,MOTO,MULTIPLE,MOTO-MULTIPLE
174,2017-0040,1,2017-04-03,2017,4,3,09:40:00,9,CAMINO CIUDAD UNUVERSITARIA Y AV. TTE. GUIRALDES,AVENIDA,...,NaN,"GUIRALDES, INT. 2699",13,Point (102290.82648731 109281.08885461),-58.438342,-34.545604,MULTIPLE,AUTO,MULTIPLE,AUTO-MULTIPLE
225,2017-0101,1,2017-08-23,2017,8,23,10:00:00,10,AV. FCO. LACROZE Y ZAPATA,AVENIDA,...,ZAPATA,"LACROZE, FEDERICO AV. y ZAPATA",13,Point (101644.77699748 106480.78805418),-58.445375,-34.570848,MULTIPLE,PEATON,MULTIPLE,PEATON-MULTIPLE
277,2018-0003,1,2018-01-05,2018,1,5,10:12:00,10,"Pueyrredon, Honorio, Dr. Av. y Galicia",AVENIDA,...,GALICIA,"PUEYRREDON, HONORIO, DR. AV. y GALICIA",15,Point (101348.13972450 102808.02053976),-58.448602,-34.603957,MULTIPLE,PEATON,MULTIPLE,PEATON-MULTIPLE
278,2018-0004,1,2018-01-09,2018,1,9,09:40:00,9,Del Libertador Av. y Manzanares,AVENIDA,...,MANZANARES,DEL LIBERTADOR AV. y MANZANARES,13,Point (100183.96103971 109533.84269558),-58.461295,-34.543328,MULTIPLE,MOTO,MULTIPLE,MOTO-MULTIPLE
333,2018-0059,1,2018-06-08,2018,6,8,06:20:00,6,"Garay, Juan De Av. y Sanchez De Loria",AVENIDA,...,SANCHEZ DE LORIA,"GARAY, JUAN DE AV. y SANCHEZ DE LORIA",5,Point (104724.05358972 99878.51159963),-58.411782,-34.630355,MOTO-MOVIL,MOTO,OTRO,MOTO-OTRO
355,2018-0081,1,2018-07-29,2018,7,29,06:30:00,6,Castañares Av. y Rivera Indarte Av.,AVENIDA,...,RIVERA INDARTE AV.,CASTAÃ‘ARES AV. y RIVERA INDARTE AV.,7,Point (101453.89687005 98180.39027169),-58.447442,-34.645672,MULTIPLE,PEATON,MULTIPLE,PEATON-MULTIPLE
371,2018-0097,1,2018-09-02,2018,9,2,10:50:00,10,Av. Varela y Av. Int. Francisco Rabanal,AVENIDA,...,"RABANAL, FRANCISCO, INTENDENTE AV.","VARELA AV. y RABANAL, FRANCISCO, INTENDENTE AV.",8,Point (102819.52927414 96448.46140692),-58.432540,-34.661281,AUTO-MOVIL,AUTO,OTRO,AUTO-OTRO
375,2018-0101,1,2018-09-21,2018,9,21,00:15:00,0,"Paz, Gral. Av. y Zapiola",GRAL PAZ,...,ZAPIOLA,"PAZ, GRAL. AV. y ZAPIOLA",12,Point (98376.44189669 109821.71138325),-58.480986,-34.540731,MULTIPLE,AUTO,MULTIPLE,AUTO-MULTIPLE
425,2019-0008,1,2019-01-30,2019,1,30,22:45:00,22,"PAZ, GRAL. AV. 16080",GRAL PAZ,...,NaN,"PAZ, GRAL. AV. 16080",8,Point (98650.97430792 93088.91481914),-58.478023,-34.691568,MULTIPLE,MOTO,MULTIPLE,MOTO-MULTIPLE
444,2019-0027,1,2019-03-28,2019,3,28,11:11:00,11,SANTA FE AV. Y AZCUENAGA,AVENIDA,...,AZCUENAGA,SANTA FE AV. y AZCUENAGA,2,Point (105815.73438780 103786.90549585),-58.399903,-34.595117,MULTIPLE,BICICLETA,MULTIPLE,BICICLETA-MULTIPLE
458,2019-0041,1,2019-05-11,2019,5,11,20:30:00,20,"ALBERDI, JUAN BAUTISTA AV. Y ANDALGALA",AVENIDA,...,ANDALGALA,"ALBERDI, JUAN BAUTISTA AV. y ANDALGALA",9,Point (95590.61347415 96760.29404728),-58.511403,-34.658464,MULTIPLE,AUTO,MULTIPLE,AUTO-MULTIPLE
513,2019-0097,1,2019-11-25,2019,11,25,08:50:00,8,"AUTOPISTA PERITO MORENO KM 5,6",AUTOPISTA,...,NaN,AUTOPISTA PERITO MORENO KM. 5.6,9,Point (98724.36593359 97905.39654686),-58.477214,-34.648151,MULTIPLE,MOTO,MULTIPLE,MOTO-MULTIPLE
550,2020-0030,1,2020-06-16,2020,6,16,15:00:00,15,SAN MARTIN AV. 1550,AVENIDA,...,NaN,SAN MARTIN AV. 1550,6,Point (101074.10089886 102529.69706887),-58.451589,-34.606466,MULTIPLE,MOTO,MULTIPLE,MOTO-MULTIPLE
643,2021-0045,1,2021-05-26,2021,5,26,17:24:00,17,AU FRONDIZI Y SUAREZ AV.,AUTOPISTA,...,NaN,AUTOPISTA 1 SUR PRESIDENTE ARTURO FRONDIZI y S...,4,Point (107903.91828587 98767.43091425),-58.377093,-34.640351,MULTIPLE,MOTO,MULTIPLE,MOTO-MULTIPLE
672,2021-0074,1,2021-09-20,2021,9,20,15:00:00,15,"PAZ, GRAL. AV. Y BALBIN, RICARDO, DR. AV.",GRAL PAZ,...,"BALBIN, RICARDO, DR. AV.","PAZ, GRAL. AV. y BALBIN, RICARDO, DR. AV.",12,Point (96563.66494817 108815.73881056),-58.500738,-34.549795,MULTIPLE,MOTO,MULTIPLE,MOTO-MULTIPLE

Cuando `PARTICIPANTES` toma el valor de "MOTO-MOVIL" o "AUTO-MOVIL" se observa una valor de "OTRO" en la variable `ACUSADO` lo cual no es consistente, por lo que se procedera a realizar una transformación.

In [174]:
mask = (hechos['PARTICIPANTES'] == 'MOTO-MOVIL') | (hechos['PARTICIPANTES'] == 'AUTO-MOVIL')
hechos.loc[mask, 'ACUSADO'] = 'MOVIL'

In [175]:
hechos.drop(columns=['PARTICIPANTES_TEORICO'], inplace=True)

### Procesamiento de la tabla `victimas`

In [176]:
victimas

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
0,2016-0001,2016-01-01,2016,1,1,CONDUCTOR,MOTO,MASCULINO,19,2016-01-01 00:00:00
1,2016-0002,2016-01-02,2016,1,2,CONDUCTOR,AUTO,MASCULINO,70,2016-01-02 00:00:00
2,2016-0003,2016-01-03,2016,1,3,CONDUCTOR,MOTO,MASCULINO,30,2016-01-03 00:00:00
3,2016-0004,2016-01-10,2016,1,10,CONDUCTOR,MOTO,MASCULINO,18,SD
4,2016-0005,2016-01-21,2016,1,21,CONDUCTOR,MOTO,MASCULINO,29,2016-02-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...
712,2021-0092,2021-12-12,2021,12,12,PEATON,PEATON,FEMENINO,50,2021-12-12 00:00:00
713,2021-0093,2021-12-13,2021,12,13,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,18,2021-12-18 00:00:00
714,2021-0094,2021-12-20,2021,12,20,PASAJERO_ACOMPAÑANTE,MOTO,FEMENINO,43,2021-12-20 00:00:00
715,2021-0095,2021-12-30,2021,12,30,CONDUCTOR,MOTO,MASCULINO,27,2022-01-02 00:00:00
716,2021-0096,2021-12-15,2021,12,15,CONDUCTOR,AUTO,MASCULINO,60,2021-12-20 00:00:00

In [177]:
victimas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_hecho             717 non-null    object
 1   FECHA                717 non-null    datetime64[ns]
 2   AAAA                 717 non-null    int64
 3   MM                   717 non-null    int64
 4   DD                   717 non-null    int64
 5   ROL                  717 non-null    object
 6   VICTIMA              717 non-null    object
 7   SEXO                 717 non-null    object
 8   EDAD                 717 non-null    object
 9   FECHA_FALLECIMIENTO  717 non-null    object
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 56.1+ KB

### Reporte Preliminar de la Tabla "Víctimas"

La tabla "Víctimas" consta de 717 entradas y 10 columnas, ofreciendo información detallada sobre cada víctima relacionada con los hechos registrados. A continuación, se presenta un análisis preliminar de cada variable contenida en la tabla:

1. **ID_hecho**: Con 717 registros no nulos, esta columna sirve como identificador único para cada hecho, vinculando potencialmente cada víctima a un incidente específico en la tabla principal de hechos. La integridad completa de esta variable facilita la correlación y el análisis conjunto con otras tablas.

2. **FECHA**: Presenta la fecha del hecho asociado a cada víctima. Al igual que `ID_hecho`, cuenta con 717 valores no nulos, permitiendo análisis temporales detallados y correlaciones con eventos específicos.

3. **AAAA**, **MM**, **DD**: Estas columnas descomponen la fecha del hecho en año, mes y día, respectivamente, lo cual simplifica la realización de análisis por períodos específicos y facilita la identificación de patrones o tendencias temporales.

4. **ROL**: Con 717 valores no nulos, esta columna describe el papel o la relación de la víctima con el hecho. La completitud de los datos en esta variable es clave para entender la dinámica de los incidentes y realizar análisis demográficos o psicosociales.

5. **VICTIMA**: También completa para todos los registros, proporciona el nombre o identificador de la víctima. Esto es crucial para análisis individuales o para identificar posibles víctimas recurrentes en diferentes hechos.

6. **SEXO**: Con 717 registros no nulos, indica el género de cada víctima. Esta variable es fundamental para realizar estudios de género y entender la distribución de los hechos según el sexo de las víctimas.

7. **EDAD**: Esta columna, completa en todos los registros, ofrece la edad de las víctimas en el momento del hecho. La disponibilidad completa de esta información permite realizar análisis demográficos detallados y entender mejor las poblaciones afectadas por los hechos registrados.

8. **FECHA_FALLECIMIENTO**: Aunque se marca como no nula para todos los registros, esta columna podría contener valores indicativos de que no todas las víctimas fallecieron (por ejemplo, fechas de fallecimiento ficticias o indicadores de no aplicabilidad). Es crucial para análisis de mortalidad y puede requerir una inspección más detallada para identificar correctamente los casos de fallecimiento real.

# ID_hecho

In [178]:
# Verificar ID duplicados

victimas['ID_hecho'].duplicated().sum()

21

En este caso, la variable `ID_hecho` se presenta como un identificador único para cada hecho, permitiendo la correlación con la tabla principal de hechos. Se detectan duplicados debido a que hay mas de una victima por hecho, por lo que no se realizaran transformaciones.

# FECHA, AAAA, MM, DD

In [179]:
victimas[['FECHA', 'AAAA', 'MM', 'DD']].dtypes

FECHA    datetime64[ns]
AAAA              int64
MM                int64
DD                int64
dtype: object

In [180]:
victimas['FECHA'].describe()

count                              717
mean     2018-09-09 01:36:24.100418304
min                2016-01-01 00:00:00
25%                2017-04-01 00:00:00
50%                2018-07-07 00:00:00
75%                2019-12-18 00:00:00
max                2021-12-30 00:00:00
Name: FECHA, dtype: object

In [181]:
print(victimas['AAAA'].unique())
print(victimas['MM'].unique())
print(victimas['DD'].unique())

[2016 2017 2018 2019 2020 2021]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3 10 21 24 29  8 14 15 17 28  4 12 13 19 23 30 31 11 20 22 25 26
 16 18 27  7  9  5  6]

Las variables presentan consistencia con el diccionario de datos, por lo que no se realizaran transformaciones.

# ROL, VICTIMA

In [182]:
print(victimas['ROL'].unique())
print(victimas['VICTIMA'].unique())

['CONDUCTOR' 'PASAJERO_ACOMPAÑANTE' 'PEATON' 'SD' 'CICLISTA']
['MOTO' 'AUTO' 'PEATON' 'SD' 'CARGAS' 'BICICLETA' 'PASAJEROS' 'MOVIL']

Se detectaron registros con valores no especificados para los dos variables, se procedera a eliminar estos registros.

In [183]:
con1 = (victimas['VICTIMA'] == 'SD')
con2 = (victimas['ROL'] == 'SD')
victimas[con1 | con2]

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
36,2016-0049,2016-04-17,2016,4,17,SD,SD,SD,SD,SD
39,2016-0052,2016-04-20,2016,4,20,SD,MOTO,SD,SD,SD
63,2016-0085,2016-06-29,2016,6,29,SD,MOTO,MASCULINO,SD,SD
77,2016-0101,2016-08-07,2016,8,7,SD,SD,MASCULINO,67,SD
89,2016-0115,2016-09-02,2016,9,2,SD,SD,MASCULINO,SD,SD
93,2016-0119,2016-09-04,2016,9,4,PASAJERO_ACOMPAÑANTE,SD,FEMENINO,SD,SD
141,2016-0174,2016-12-27,2016,12,27,SD,SD,SD,SD,SD
167,2017-0029,2017-03-07,2017,3,7,SD,SD,MASCULINO,34,2017-03-07 00:00:00
208,2017-0074,2017-06-04,2017,6,4,SD,SD,MASCULINO,70,2017-06-04 00:00:00
221,2017-0089,2017-07-13,2017,7,13,SD,SD,MASCULINO,23,SD
280,2017-0155,2017-12-12,2017,12,12,SD,SD,MASCULINO,77,SD
390,2018-0100,2018-09-20,2018,9,20,SD,MOTO,FEMENINO,33,2018-09-20 00:00:00

In [184]:
victimas = victimas[~(con1 | con2)]

#   SEXO, EDAD

In [185]:
print(victimas['SEXO'].unique())
print(victimas['EDAD'].unique())

['MASCULINO' 'FEMENINO' 'SD']
[19 70 30 18 29 22 16 59 65 34 41 50 38 21 52 36 20 54 'SD' 56 24 78 79 26
 57 37 58 23 60 42 53 51 40 87 76 75 35 80 43 45 27 55 49 67 81 25 33 46
 83 39 28 7 48 4 82 32 17 47 61 10 95 73 84 66 85 1 15 13 44 31 62 74 71
 11 86 69 72 12 77 63 92 68 91 64 5 88]

- `SEXO` : Es consistente con el diccionario de datos, contiene datos sin especificar que se deben tratar.
- `EDAD` : Los rangos de edad observados son consistentes, contiene datos sin especificar que se deben tratar.

In [186]:
victimas[victimas['SEXO'] == "SD"]

,ID_hecho,FECHA,AAAA,MM,DD,ROL,VICTIMA,SEXO,EDAD,FECHA_FALLECIMIENTO
108,2016-0136,2016-10-25,2016,10,25,CONDUCTOR,MOTO,SD,SD,SD
121,2016-0151,2016-11-18,2016,11,18,PEATON,PEATON,SD,SD,SD
138,2016-0171,2016-12-25,2016,12,25,CONDUCTOR,MOTO,SD,SD,SD

In [187]:
victimas = victimas[victimas['SEXO'] != "SD"]

In [188]:
victimas[victimas['EDAD'] == "SD"].shape[0] / victimas.shape[0] * 100

6.267806267806268

Al ser 44 datos sin especificar, lo que representa aproximadamente el 6% del total de los registros, se realizara una imputación para no perder tanta información que puede influir en los resultados finales.

In [189]:
# Tomar SD y reemplazar por la moda

victimas['EDAD'] = victimas['EDAD'].replace('SD', pd.NA)

In [190]:
victimas['EDAD'].fillna(victimas['EDAD'].mode().iloc[0], inplace=True)

# FECHA_FALLECIMIENTO

Se especificaran los valores SD como NA, y se transformara el tipo de dato a datetime64[ns].

In [191]:
victimas['FECHA_FALLECIMIENTO'].replace('SD', pd.NA, inplace=True)

In [192]:
victimas['FECHA_FALLECIMIENTO'] = pd.to_datetime(
    victimas['FECHA_FALLECIMIENTO'], errors='coerce')

# Unificación de las tablas y exportación 

Se unificaran las tablas `hechos` y `victimas` mediante la variable `ID`, se mantendran las variables que se consideren relevantes para el análisis exploratorio de datos y se exportara el resultado a un archivo csv.

In [193]:
victimas.drop(columns=['FECHA', 'AAAA', 'MM', 'DD',
              'FECHA_FALLECIMIENTO', 'VICTIMA'], inplace=True)



victimas

      ID_hecho                   ROL       SEXO  EDAD
0    2016-0001             CONDUCTOR  MASCULINO    19
1    2016-0002             CONDUCTOR  MASCULINO    70
2    2016-0003             CONDUCTOR  MASCULINO    30
3    2016-0004             CONDUCTOR  MASCULINO    18
4    2016-0005             CONDUCTOR  MASCULINO    29
..         ...                   ...        ...   ...
712  2021-0092                PEATON   FEMENINO    50
713  2021-0093  PASAJERO_ACOMPAÑANTE   FEMENINO    18
714  2021-0094  PASAJERO_ACOMPAÑANTE   FEMENINO    43
715  2021-0095             CONDUCTOR  MASCULINO    27
716  2021-0096             CONDUCTOR  MASCULINO    60

[702 rows x 4 columns]

In [194]:
hechos.drop(columns=['Altura', 'Cruce'], inplace=True)

In [195]:
hechos.query('VICTIMA == "OBJETO FIJO"')

Empty DataFrame
Columns: [ID, N_VICTIMAS, FECHA, AAAA, MM, DD, HORA, HH, LUGAR_DEL_HECHO, TIPO_DE_CALLE, Calle, Dirección Normalizada, COMUNA, XY (CABA), pos x, pos y, PARTICIPANTES, VICTIMA, ACUSADO]
Index: []

In [196]:
homicidios = hechos.merge(victimas, left_on='ID', right_on='ID_hecho')

In [197]:
homicidios.drop(columns=['ID_hecho'], inplace=True)

In [198]:
homicidios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 687 entries, 0 to 686
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     687 non-null    object
 1   N_VICTIMAS             687 non-null    int64
 2   FECHA                  687 non-null    datetime64[ns]
 3   AAAA                   687 non-null    int64
 4   MM                     687 non-null    int64
 5   DD                     687 non-null    int64
 6   HORA                   687 non-null    object
 7   HH                     687 non-null    object
 8   LUGAR_DEL_HECHO        687 non-null    object
 9   TIPO_DE_CALLE          687 non-null    object
 10  Calle                  687 non-null    object
 11  Dirección Normalizada  687 non-null    object
 12  COMUNA                 687 non-null    object
 13  XY (CABA)              687 non-null    object
 14  pos x                  687 non-null    float64
 15  pos y                  687 non-null    float64
 16  PARTICIPANTES          687 non-null    object
 17  VICTIMA                687 non-null    object
 18  ACUSADO                687 non-null    object
 19  ROL                    687 non-null    object
 20  SEXO                   687 non-null    object
 21  EDAD                   687 non-null    int64
dtypes: datetime64[ns](1), float64(2), int64(5), object(14)
memory usage: 118.2+ KB

In [199]:
homicidios

,ID,N_VICTIMAS,FECHA,AAAA,MM,DD,HORA,HH,LUGAR_DEL_HECHO,TIPO_DE_CALLE,...,COMUNA,XY (CABA),pos x,pos y,PARTICIPANTES,VICTIMA,ACUSADO,ROL,SEXO,EDAD
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,8,Point (98896.78238426 93532.43437792),-58.475340,-34.687570,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,19
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,9,Point (95832.05571093 95505.41641999),-58.508775,-34.669777,AUTO-PASAJEROS,AUTO,PASAJEROS,CONDUCTOR,MASCULINO,70
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,1,Point (106684.29090040 99706.57687843),-58.390403,-34.631894,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,30
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,8,Point (99840.65224780 94269.16534422),-58.465039,-34.680930,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,18
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,1,Point (106980.32827929 100752.16915795),-58.387183,-34.622466,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
682,2021-0093,1,2021-12-13,2021,12,13,17:10:00,17,AV. RIESTRA Y MOM,AVENIDA,...,7,Point (102728.60090138 98186.24929177),-58.433538,-34.645616,MOTO-AUTO,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,18
683,2021-0094,1,2021-12-20,2021,12,20,01:10:00,1,AU DELLEPIANE Y LACARRA,AUTOPISTA,...,9,Point (99624.29795829 97569.69801131),-58.467398,-34.651178,MOTO-AUTO,MOTO,AUTO,PASAJERO_ACOMPAÑANTE,FEMENINO,43
684,2021-0095,1,2021-12-30,2021,12,30,00:43:00,0,AV. GAONA Y TERRADA,AVENIDA,...,11,Point (99116.45492358 101045.23284826),-58.472934,-34.619847,MOTO-CARGAS,MOTO,CARGAS,CONDUCTOR,MASCULINO,27
685,2021-0096,1,2021-12-15,2021,12,15,10:30:00,10,AV. EVA PERON 4071,AVENIDA,...,9,Point (99324.54463985 97676.26932409),-58.470668,-34.650217,AUTO-CARGAS,AUTO,CARGAS,CONDUCTOR,MASCULINO,60
686,2021-0097,1,2021-11-18,2021,11,18,06:10:00,6,PADRE CARLOS MUJICA 709,CALLE,...,1,Point (107664.16647795 104708.63962087),-58.379762,-34.586796,BICICLETA-AUTO,BICICLETA,AUTO,CICLISTA,MASCULINO,53

In [200]:

# Renombrar columnas para que an
homicidios.rename(columns={
    "ID": "id_caso",
    "N_VICTIMAS": "num_victimas",
    "FECHA": "fecha",
    "AAAA": "anio",
    "MM": "mes",
    "DD": "dia",
    "HORA": "hora",
    "HH": "hora_exacta",
    "LUGAR_DEL_HECHO": "lugar_hecho",
    "TIPO_DE_CALLE": "tipo_calle",
    "Calle": "nombre_calle",
    "Dirección Normalizada": "direccion_normalizada",
    "COMUNA": "comuna",
    "XY (CABA)": "coordenadas_planas",
    "pos x": "lon",
    "pos y": "lat",
    "PARTICIPANTES": "participantes",
    "VICTIMA": "victima",
    "ACUSADO": "acusado",
    "ROL": "rol_participante",
    "SEXO": "sexo",
    "EDAD": "edad"
}, inplace=True)

# Verificar los cambios
homicidios.head()

,id_caso,num_victimas,fecha,anio,mes,dia,hora,hora_exacta,lugar_hecho,tipo_calle,...,comuna,coordenadas_planas,lon,lat,participantes,victima,acusado,rol_participante,sexo,edad
0,2016-0001,1,2016-01-01,2016,1,1,04:00:00,4,AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ,AVENIDA,...,8,Point (98896.78238426 93532.43437792),-58.475340,-34.687570,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,19
1,2016-0002,1,2016-01-02,2016,1,2,01:15:00,1,AV GRAL PAZ Y AV DE LOS CORRALES,GRAL PAZ,...,9,Point (95832.05571093 95505.41641999),-58.508775,-34.669777,AUTO-PASAJEROS,AUTO,PASAJEROS,CONDUCTOR,MASCULINO,70
2,2016-0003,1,2016-01-03,2016,1,3,07:00:00,7,AV ENTRE RIOS 2034,AVENIDA,...,1,Point (106684.29090040 99706.57687843),-58.390403,-34.631894,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,30
3,2016-0004,1,2016-01-10,2016,1,10,00:00:00,0,AV LARRAZABAL Y GRAL VILLEGAS CONRADO,AVENIDA,...,8,Point (99840.65224780 94269.16534422),-58.465039,-34.680930,MOTO-AUTO,MOTO,AUTO,CONDUCTOR,MASCULINO,18
4,2016-0005,1,2016-01-21,2016,1,21,05:20:00,5,AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA,AVENIDA,...,1,Point (106980.32827929 100752.16915795),-58.387183,-34.622466,MOTO-PASAJEROS,MOTO,PASAJEROS,CONDUCTOR,MASCULINO,29

In [201]:
homicidios.rol_participante.unique()

array(['CONDUCTOR', 'PASAJERO_ACOMPAÑANTE', 'PEATON', 'CICLISTA'],
      dtype=object)

In [202]:
# Recodificar los valores de la columna tipo_calle 
homicidios['tipo_calle'] = homicidios['tipo_calle'].replace({
    'AVENIDA': 'Avenida',
    'GRAL PAZ': 'General Paz',
    'CALLE': 'Calle',
    'AUTOPISTA': 'Autopista'
})

# Recodificar los valores de la columna rol_participante array(['CONDUCTOR', 'PASAJERO_ACOMPAÑANTE', 'PEATON', 'CICLISTA'],
homicidios['rol_participante'] = homicidios['rol_participante'].replace({
    'CONDUCTOR': 'Conductor',
    'PASAJERO_ACOMPAÑANTE': 'Pasajero Acompañante',
    'PEATON': 'Peatón',
    'CICLISTA': 'Ciclista'
})

# Recodificar los valores de la columna victima

homicidios['victima'] = homicidios['victima'].replace({
    'MOTO': 'Moto',
    'AUTO': 'Automóvil',
    'PEATON': 'Peatón',
    'CARGAS': 'Cargas',
    'BICICLETA': 'Bicicleta',
    'PASAJEROS': 'Pasajeros',
    'MOVIL': 'Móvil'
})
# Recodificar los valores de la columna acusado

homicidios['acusado'] = homicidios['acusado'].replace({
    'AUTO': 'Automóvil',
    'PASAJEROS': 'Pasajeros',
    'OBJETO FIJO': 'Objeto Fijo',
    'CARGAS': 'Cargas',
    'MOTO': 'Moto',
    'MULTIPLE': 'Múltiple',
    'BICICLETA': 'Bicicleta',
    'MOVIL': 'Móvil',
    'TREN': 'Tren',
    'OTRO': 'Otro'
})

In [134]:
homicidios.to_excel("./data/homicidios_clean.xlsx", index=False)